package governance

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

// ExecutableCanonicalVectorV1 is a generated byte vector, not a metadata
// recipe. FalsePredicateIDs is populated for predicate-negative vectors.
type ExecutableCanonicalVectorV1 struct {
	VectorID          string
	Bytes             []byte
	RequiredError     CanonicalRequiredError
	FalsePredicateIDs []string
}

type ExecutableCanonicalVectorSetV1 struct {
	SchemaID   string
	Positive   []byte
	Rejections []ExecutableCanonicalVectorV1
}

// GenerateCanonicalCatalogPositiveVectorsV1 materializes the complete frozen
// positive corpus. Record-valued fields and arrays are resolved recursively,
// so the result never substitutes an empty object for a required record.
func GenerateCanonicalCatalogPositiveVectorsV1(catalog CanonicalVectorCatalogV1) (map[string][]byte, error) {
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	byRecord := make(map[string]CanonicalVectorEntryV1, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		if prior, duplicate := byRecord[entry.RecordName]; duplicate && prior.SchemaID != entry.SchemaID {
			return nil, fmt.Errorf("record target %s is ambiguous", entry.RecordName)
		}
		byRecord[entry.RecordName] = entry
	}
	result := make(map[string][]byte, len(catalog.Entries))
	visiting := make(map[string]bool)
	var generate func(CanonicalVectorEntryV1) ([]byte, error)
	generate = func(entry CanonicalVectorEntryV1) ([]byte, error) {
		if positive, ok := result[entry.SchemaID]; ok {
			return append([]byte(nil), positive...), nil
		}
		if visiting[entry.SchemaID] {
			return nil, fmt.Errorf("required record target cycle at %s", entry.SchemaID)
		}
		visiting[entry.SchemaID] = true
		defer delete(visiting, entry.SchemaID)
		positive, err := GenerateMinimalCanonicalVectorV1(entry)
		if err != nil {
			return nil, err
		}
		if entry.RecordName == "ArtifactBlobV1" && entry.SchemaID == "artifact-blob-v1" {
			result[entry.SchemaID] = append([]byte(nil), positive...)
			return positive, nil
		}
		values, _, _, err := decodeCanonicalVectorObjectV1(positive)
		if err != nil {
			return nil, err
		}
		for _, field := range entry.Fields {
			raw, present := values[field.FieldPath]
			if !present {
				continue
			}
			switch field.JSONType {
			case WireObject:
				target, ok := byRecord[field.RecordTarget]
				if !ok {
					// Retained predecessor records are validated by their frozen V1
					// constructors and are not duplicated in the V4 catalog.
					continue
				}
				values[field.FieldPath], err = generate(target)
			case WireArray:
				targetName := field.RecordTarget
				if targetName == "" {
					elementType := arrayElementTypeV1(field.ValueType)
					if target, ok := byRecord[elementType]; ok {
						targetName = target.RecordName
					}
				}
				if targetName == "" {
					continue
				}
				target, ok := byRecord[targetName]
				if !ok {
					continue
				}
				var elements []json.RawMessage
				if json.Unmarshal(raw, &elements) != nil {
					return nil, fmt.Errorf("%s.%s positive is not an array", entry.SchemaID, field.FieldPath)
				}
				for index := range elements {
					elements[index], err = generate(target)
					if err != nil {
						break
					}
				}
				if err == nil {
					values[field.FieldPath], err = json.Marshal(elements)
				}
			}
			if err != nil {
				return nil, err
			}
		}
		if err := applyPositivePredicatesV1(entry, values); err != nil {
			return nil, err
		}
		if err := applyEd25519VectorsV1(entry, values); err != nil {
			return nil, err
		}
		for index, field := range entry.Fields {
			if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, index) {
				continue
			}
			preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
			if err != nil {
				return nil, err
			}
			values[field.FieldPath], _ = json.Marshal(sha256Hex(preimage))
		}
		positive, err = marshalCanonicalVectorObjectV1(entry.Fields, values, "")
		if err != nil {
			return nil, err
		}
		result[entry.SchemaID] = append([]byte(nil), positive...)
		return positive, nil
	}
	for _, entry := range catalog.Entries {
		if _, err := generate(entry); err != nil {
			return nil, err
		}
	}
	for _, entry := range catalog.Entries {
		if err := validateCanonicalCatalogPositiveV1(entry, result[entry.SchemaID], byRecord, make(map[string]bool)); err != nil {
			return nil, fmt.Errorf("validate %s positive: %w", entry.SchemaID, err)
		}
	}
	return result, nil
}

func validateCanonicalCatalogPositiveV1(entry CanonicalVectorEntryV1, data []byte, byRecord map[string]CanonicalVectorEntryV1, visiting map[string]bool) error {
	if err := validateCanonicalVectorBytesV1(entry, data); err != nil {
		return err
	}
	if entry.RecordName == "ArtifactBlobV1" {
		return nil
	}
	if visiting[entry.SchemaID] {
		return errors.New("record target cycle")
	}
	visiting[entry.SchemaID] = true
	defer delete(visiting, entry.SchemaID)
	values, _, _, err := decodeCanonicalVectorObjectV1(data)
	if err != nil {
		return err
	}
	for _, field := range entry.Fields {
		raw, present := values[field.FieldPath]
		if !present {
			continue
		}
		targetName := field.RecordTarget
		if targetName == "" && field.JSONType == WireArray {
			targetName = arrayElementTypeV1(field.ValueType)
		}
		target, ok := byRecord[targetName]
		if !ok {
			continue
		}
		if field.JSONType == WireObject {
			if err := validateCanonicalCatalogPositiveV1(target, raw, byRecord, visiting); err != nil {
				return fmt.Errorf("field %s: %w", field.FieldPath, err)
			}
		}
		if field.JSONType == WireArray {
			var elements []json.RawMessage
			if json.Unmarshal(raw, &elements) != nil {
				return fmt.Errorf("field %s is not an array", field.FieldPath)
			}
			for index, element := range elements {
				if err := validateCanonicalCatalogPositiveV1(target, element, byRecord, visiting); err != nil {
					return fmt.Errorf("field %s[%d]: %w", field.FieldPath, index, err)
				}
			}
		}
	}
	return nil
}

type canonicalVectorValidationErrorV1 struct {
	code            CanonicalRequiredError
	path            string
	falsePredicates []string
}

func (e *canonicalVectorValidationErrorV1) Error() string {
	if len(e.falsePredicates) != 0 {
		return fmt.Sprintf("%s: predicates %s", e.code, strings.Join(e.falsePredicates, ","))
	}
	if e.path != "" {
		return fmt.Sprintf("%s: field %s", e.code, e.path)
	}
	return string(e.code)
}

// ValidateCanonicalVectorBytesV1 mechanically validates one record against
// the extracted descriptors and executable predicate subset. It is also used
// by generation, so a recipe can never be reported as an executable vector
// unless its bytes actually produce the frozen result class.
func ValidateCanonicalVectorBytesV1(entry CanonicalVectorEntryV1, data []byte) error {
	return validateCanonicalVectorBytesV1(entry, data)
}

// GenerateExecutableCanonicalVectorsV1 materializes and validates the
// positive vector and every rejection recipe carried by an entry.
func GenerateExecutableCanonicalVectorsV1(entry CanonicalVectorEntryV1) (ExecutableCanonicalVectorSetV1, error) {
	positive, err := GenerateMinimalCanonicalVectorV1(entry)
	if err != nil {
		return ExecutableCanonicalVectorSetV1{}, err
	}
	if err := validateCanonicalVectorBytesV1(entry, positive); err != nil {
		return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("positive vector for %s is invalid: %w", entry.SchemaID, err)
	}
	result := ExecutableCanonicalVectorSetV1{SchemaID: entry.SchemaID, Positive: positive, Rejections: make([]ExecutableCanonicalVectorV1, 0, len(entry.Rejections))}
	for _, recipe := range entry.Rejections {
		mutated, err := mutateCanonicalVectorV1(entry, positive, recipe)
		if err != nil {
			return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("generate %s: %w", recipe.VectorID, err)
		}
		validationErr := validateCanonicalVectorBytesV1(entry, mutated)
		var classified *canonicalVectorValidationErrorV1
		if !errors.As(validationErr, &classified) || classified.code != recipe.RequiredError {
			return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("vector %s classified as %v, want %s", recipe.VectorID, validationErr, recipe.RequiredError)
		}
		falseIDs := append([]string(nil), classified.falsePredicates...)
		sort.Strings(falseIDs)
		result.Rejections = append(result.Rejections, ExecutableCanonicalVectorV1{
			VectorID: recipe.VectorID, Bytes: mutated, RequiredError: recipe.RequiredError, FalsePredicateIDs: falseIDs,
		})
	}
	return result, nil
}

func validateCanonicalVectorBytesV1(entry CanonicalVectorEntryV1, data []byte) error {
	if entry.RecordName == "ArtifactBlobV1" && entry.SchemaID == "artifact-blob-v1" {
		if bytes.Equal(data, []byte{'a'}) {
			return nil
		}
		return &canonicalVectorValidationErrorV1{code: CanonicalBoundInvalid}
	}
	if !utf8.Valid(data) || len(data) == 0 || len(data) > 1<<20 {
		return &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	values, order, duplicate, parseErr := decodeCanonicalVectorObjectV1(data)
	if parseErr != nil {
		return &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	if duplicate {
		return &canonicalVectorValidationErrorV1{code: CanonicalDuplicateField}
	}
	descriptors := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		descriptors[field.FieldPath] = field
	}
	for _, name := range order {
		if _, ok := descriptors[name]; !ok {
			return &canonicalVectorValidationErrorV1{code: CanonicalUnknownField}
		}
	}
	expectedOrder := make([]string, 0, len(entry.Fields))
	for _, field := range entry.Fields {
		_, present := values[field.FieldPath]
		if !present && !field.Optional {
			return &canonicalVectorValidationErrorV1{code: CanonicalMissingField}
		}
		if present {
			expectedOrder = append(expectedOrder, field.FieldPath)
		}
	}
	if !equalVectorStringsV1(order, expectedOrder) {
		return &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	canonical, err := marshalCanonicalVectorObjectV1(entry.Fields, values, "")
	if err != nil || !bytes.Equal(canonical, data) {
		return &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	for _, field := range entry.Fields {
		raw, present := values[field.FieldPath]
		if !present {
			continue
		}
		if code := validateCanonicalDescriptorValueV1(field, raw); code != "" {
			return &canonicalVectorValidationErrorV1{code: code, path: field.FieldPath}
		}
	}
	for fieldIndex, field := range entry.Fields {
		if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, fieldIndex) {
			continue
		}
		var actual string
		if json.Unmarshal(values[field.FieldPath], &actual) != nil {
			return &canonicalVectorValidationErrorV1{code: CanonicalTypeInvalid, path: field.FieldPath}
		}
		preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
		if err != nil || actual != sha256Hex(preimage) {
			return &canonicalVectorValidationErrorV1{code: CanonicalDigestInvalid, path: field.FieldPath}
		}
	}
	falsePredicates := falseCanonicalPredicatesV1(entry, values)
	if len(falsePredicates) != 0 {
		return &canonicalVectorValidationErrorV1{code: CanonicalPredicateInvalid, falsePredicates: falsePredicates}
	}
	return nil
}

func equalVectorStringsV1(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func decodeCanonicalVectorObjectV1(data []byte) (map[string]json.RawMessage, []string, bool, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	token, err := decoder.Token()
	if err != nil || token != json.Delim('{') {
		return nil, nil, false, errors.New("record is not an object")
	}
	values := make(map[string]json.RawMessage)
	var order []string
	duplicate := false
	for decoder.More() {
		nameToken, err := decoder.Token()
		if err != nil {
			return nil, nil, false, err
		}
		name, ok := nameToken.(string)
		if !ok {
			return nil, nil, false, errors.New("field name is not a string")
		}
		var raw json.RawMessage
		if err := decoder.Decode(&raw); err != nil {
			return nil, nil, false, err
		}
		if _, exists := values[name]; exists {
			duplicate = true
		}
		values[name] = append(json.RawMessage(nil), raw...)
		order = append(order, name)
	}
	if token, err = decoder.Token(); err != nil || token != json.Delim('}') {
		return nil, nil, false, errors.New("record is unterminated")
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, nil, false, errors.New("record has trailing JSON")
	}
	return values, order, duplicate, nil
}

func validateCanonicalDescriptorValueV1(field WireFieldDescriptorV1, raw json.RawMessage) CanonicalRequiredError {
	if bytes.Equal(raw, []byte("null")) {
		return CanonicalTypeInvalid
	}
	switch field.JSONType {
	case WireString:
		var value string
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinBytes != nil && uint64(len(value)) < *field.MinBytes || field.MaxBytes != nil && uint64(len(value)) > *field.MaxBytes {
			return CanonicalBoundInvalid
		}
		if isClosedEnumType(field.ValueType) || strings.HasPrefix(field.ValueType, "{") {
			if err := ValidatePrimitiveWireValueV1(field.ValueType, value); err != nil {
				return CanonicalEnumInvalid
			}
		}
		var primitiveErr error
		if strings.HasPrefix(field.ValueType, "sha256<") || field.ValueType == "blob256" {
			primitiveErr = validateExactLowerHex(value, 64)
		} else {
			primitiveErr = ValidatePrimitiveWireValueV1(field.ValueType, value)
		}
		if primitiveErr != nil {
			if field.ValueType == "absPath" && strings.HasPrefix(value, "/") && strings.Contains(value, "/../") {
				return CanonicalNonCanonical
			}
			return CanonicalBoundInvalid
		}
	case WireInteger:
		var value uint64
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinU64 != nil && value < *field.MinU64 || field.MaxU64 != nil && value > *field.MaxU64 {
			return CanonicalBoundInvalid
		}
	case WireBoolean:
		var value bool
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
	case WireArray:
		var values []json.RawMessage
		if json.Unmarshal(raw, &values) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinItems != nil && uint64(len(values)) < *field.MinItems || field.MaxItems != nil && uint64(len(values)) > *field.MaxItems {
			return CanonicalBoundInvalid
		}
		if strings.Contains(field.ValueType, "(set") {
			for index := 1; index < len(values); index++ {
				comparison := bytes.Compare(values[index-1], values[index])
				if comparison >= 0 {
					return CanonicalOrderInvalid
				}
			}
		}
		elementType := arrayElementTypeV1(field.ValueType)
		if elementType != "" && !(strings.HasSuffix(elementType, "V1") || strings.HasSuffix(elementType, "V2") || strings.HasSuffix(elementType, "V3") || strings.HasSuffix(elementType, "V4")) {
			descriptor, err := ResolveWireFieldDescriptorV1(field.SchemaID, field.FieldPath, field.Ordinal, elementType, false)
			if err != nil {
				return CanonicalTypeInvalid
			}
			for _, value := range values {
				if code := validateCanonicalDescriptorValueV1(descriptor, value); code != "" {
					return code
				}
			}
		}
	case WireObject:
		if len(raw) == 0 || raw[0] != '{' || !json.Valid(raw) {
			return CanonicalTypeInvalid
		}
	case WireRawJSON:
		if !json.Valid(raw) {
			return CanonicalTypeInvalid
		}
	default:
		return CanonicalTypeInvalid
	}
	return ""
}

func sha256Hex(data []byte) string {
	digest := sha256.Sum256(data)
	return hex.EncodeToString(digest[:])
}

func falseCanonicalPredicatesV1(entry CanonicalVectorEntryV1, values map[string]json.RawMessage) []string {
	var result []string
	fields := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		fields[field.FieldPath] = field
	}
	for _, predicate := range entry.Predicates {
		valid := true
		switch predicate.Operator {
		case PredicateExactLiteral:
			if len(predicate.FieldPaths) != 1 || len(predicate.Arguments) == 0 {
				valid = false
				break
			}
			raw, present := values[predicate.FieldPaths[0]]
			if !present {
				valid = false
				break
			}
			field, fieldFound := canonicalVectorFieldV1(entry.Fields, predicate.FieldPaths[0])
			if !fieldFound {
				valid = false
				break
			}
			switch field.JSONType {
			case WireString:
				var scalar string
				valid = json.Unmarshal(raw, &scalar) == nil && scalar == predicate.Arguments[0]
			case WireInteger, WireBoolean, WireArray:
				valid = string(raw) == predicate.Arguments[0]
			default:
				valid = false
			}
		case PredicateAllEqual:
			if len(predicate.FieldPaths) > 1 {
				first, present := values[predicate.FieldPaths[0]]
				valid = present
				for _, path := range predicate.FieldPaths[1:] {
					next, ok := values[path]
					valid = valid && ok && bytes.Equal(first, next)
				}
			}
		case PredicateExactlyOne:
			count := 0
			for _, path := range predicate.FieldPaths {
				if _, present := values[path]; present {
					count++
				}
			}
			valid = count == 1
		case PredicateSubset:
			if len(predicate.FieldPaths) >= 2 {
				var subset, superset []json.RawMessage
				if json.Unmarshal(values[predicate.FieldPaths[0]], &subset) != nil || json.Unmarshal(values[predicate.FieldPaths[1]], &superset) != nil {
					valid = false
				} else {
					members := make(map[string]struct{}, len(superset))
					for _, value := range superset {
						members[string(value)] = struct{}{}
					}
					for _, value := range subset {
						_, ok := members[string(value)]
						valid = valid && ok
					}
				}
			}
		case PredicateOrdinalSuccess:
			paths := integerPredicatePathsV1(predicate.FieldPaths, fields)
			if len(paths) >= 2 {
				var predecessor, successor uint64
				valid = json.Unmarshal(values[paths[0]], &predecessor) == nil && json.Unmarshal(values[paths[1]], &successor) == nil && successor == predecessor+1
			}
		case PredicateDigestPreimage:
			// Self-digests were already checked against exact bytes above.
		case PredicateTypedReference:
			if !strings.Contains(predicate.PredicateID, "-TYPED_REFERENCE-") {
				break
			}
			for _, path := range predicate.FieldPaths {
				field, ok := fields[path]
				if !ok {
					valid = false
					continue
				}
				raw, present := values[path]
				if !present {
					continue
				}
				expected, err := minimalDescriptorJSON(field)
				valid = valid && err == nil && bytes.Equal(raw, expected)
			}
		case PredicateIfAndOnlyIf, PredicateImplies, PredicateStateTransition, PredicateDerivation, PredicateAggregateLEQ:
			// These predicates are mechanically enumerated from normalized prose.
			// Their positive minimal forms use false antecedents/minimal counters;
			// named negative mutations below make an explicit operand false.
		}
		if !valid {
			result = append(result, predicate.PredicateID)
		}
	}
	sort.Strings(result)
	return result
}

func mutateCanonicalVectorV1(entry CanonicalVectorEntryV1, positive []byte, recipe CanonicalRejectionVectorV1) ([]byte, error) {
	values, _, _, err := decodeCanonicalVectorObjectV1(positive)
	if err != nil {
		return nil, err
	}
	path, mutation := rejectionTargetAndMutationV1(entry.SchemaID, recipe.VectorID)
	if path == "$" {
		switch mutation {
		case "UNKNOWN_FIRST":
			return append([]byte(`{"__unknown":false,`), positive[1:]...), nil
		case "UNKNOWN_LAST":
			return append(append([]byte(nil), positive[:len(positive)-1]...), []byte(`,"__unknown":false}`)...), nil
		case "DUPLICATE_FIELD":
			if len(entry.Fields) == 0 {
				return nil, errors.New("record has no duplicable field")
			}
			field := entry.Fields[0]
			value, ok := values[field.FieldPath]
			if !ok {
				return nil, errors.New("first field is absent")
			}
			name, _ := json.Marshal(field.FieldPath)
			prefix := append(append(append([]byte{'{'}, name...), ':'), value...)
			prefix = append(prefix, ',')
			return append(prefix, positive[1:]...), nil
		case "INVALID_UTF8":
			result := append([]byte(nil), positive...)
			for index := 1; index < len(result)-1; index++ {
				if result[index] == 'a' {
					result[index] = 0xff
					return result, nil
				}
			}
			return append(result[:len(result)-1], []byte(",\"x\":\"\xff\"}")...), nil
		case "TRAILING_JSON":
			return append(append([]byte(nil), positive...), []byte("{}")...), nil
		}
	}
	field, ok := canonicalVectorFieldV1(entry.Fields, path)
	if !ok {
		return nil, fmt.Errorf("unknown mutation path %s", path)
	}
	if strings.HasPrefix(mutation, "PREDICATE_") {
		predicateID := strings.TrimPrefix(mutation, "PREDICATE_")
		predicate, found := canonicalVectorPredicateV1(entry.Predicates, predicateID)
		if !found {
			return nil, fmt.Errorf("unknown predicate %s", predicateID)
		}
		if err := mutatePredicateV1(entry, predicate, values); err != nil {
			return nil, err
		}
		return resealDependentDigestsV1(entry, values, predicate.FieldPaths)
	}
	switch mutation {
	case "REMOVE":
		delete(values, path)
	case "NULL":
		values[path] = []byte("null")
	case "WRONG_TYPE":
		values[path] = wrongJSONTypeV1(field.JSONType)
	case "BELOW_MIN":
		values[path], err = belowMinimumJSONV1(field)
	case "ABOVE_MAX":
		values[path], err = aboveMaximumJSONV1(field)
	case "OVERSIZE":
		values[path], err = oversizedJSONV1(field)
	case "ENUM_INVALID":
		values[path], err = invalidEnumJSONV1(field)
	case "UPPERCASE":
		values[path], err = mutateStringJSONV1(values[path], uppercaseFirstAlphaV1)
	case "SHORT":
		values[path], err = mutateStringJSONV1(values[path], func(value string) string {
			if len(value) >= 2 {
				return value[:len(value)-2]
			}
			return ""
		})
	case "BAD_CHAR":
		values[path], err = badCharacterJSONV1(field)
	case "UNSORTED":
		values[path], err = unsortedArrayJSONV1(field, values[path])
	case "DUPLICATE_MEMBER":
		values[path], err = duplicateArrayMemberJSONV1(field, values[path])
	case "CONSTANT_CHANGED":
		var changed string
		changed, err = ConstantChangedV1(field)
		if err == nil {
			values[path], err = scalarForDescriptorV1(field, changed)
		}
	case "SELF_DIGEST_MISMATCH":
		values[path], err = mutateStringJSONV1(values[path], flipFirstHexV1)
	default:
		return nil, fmt.Errorf("unsupported canonical mutation %s", mutation)
	}
	if err != nil {
		return nil, err
	}
	if mutation != "SELF_DIGEST_MISMATCH" {
		return resealDependentDigestsV1(entry, values, []string{path})
	}
	return marshalCanonicalVectorObjectV1(entry.Fields, values, "")
}

func invalidEnumJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	if field.JSONType != WireString || field.MinBytes == nil || field.MaxBytes == nil {
		return nil, errors.New("enum descriptor has no string bounds")
	}
	for length := *field.MinBytes; length <= *field.MaxBytes; length++ {
		for _, character := range []byte{'x', 'y', 'z'} {
			candidate := strings.Repeat(string(character), int(length))
			if ValidatePrimitiveWireValueV1(field.ValueType, candidate) != nil {
				return json.Marshal(candidate)
			}
		}
		if length == *field.MaxBytes {
			break
		}
	}
	return nil, errors.New("enum has no bounded invalid member")
}

func rejectionTargetAndMutationV1(schemaID, vectorID string) (string, string) {
	prefix := schemaID + "/"
	remaining := strings.TrimPrefix(vectorID, prefix)
	index := strings.LastIndexByte(remaining, '/')
	if index < 0 {
		return "$", remaining
	}
	path := remaining[:index]
	path = strings.ReplaceAll(path, "~1", "/")
	path = strings.ReplaceAll(path, "~0", "~")
	return path, remaining[index+1:]
}

func canonicalVectorFieldV1(fields []WireFieldDescriptorV1, path string) (WireFieldDescriptorV1, bool) {
	for _, field := range fields {
		if field.FieldPath == path {
			return field, true
		}
	}
	return WireFieldDescriptorV1{}, false
}

func canonicalVectorPredicateV1(predicates []PredicateDescriptorV1, id string) (PredicateDescriptorV1, bool) {
	for _, predicate := range predicates {
		if predicate.PredicateID == id {
			return predicate, true
		}
	}
	return PredicateDescriptorV1{}, false
}

func wrongJSONTypeV1(kind WireJSONType) json.RawMessage {
	if kind == WireBoolean {
		return []byte(`"wrong"`)
	}
	if kind == WireString {
		return []byte("false")
	}
	return []byte(`"wrong"`)
}

func belowMinimumJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	switch field.JSONType {
	case WireString:
		minimum := uint64(0)
		if field.MinBytes != nil {
			minimum = *field.MinBytes
		}
		if minimum == 0 {
			return nil, errors.New("string has no below-minimum value")
		}
		return json.Marshal(strings.Repeat("a", int(minimum-1)))
	case WireInteger:
		minimum := uint64(0)
		if field.MinU64 != nil {
			minimum = *field.MinU64
		}
		if minimum == 0 {
			return nil, errors.New("integer has no below-minimum value")
		}
		return []byte(strconv.FormatUint(minimum-1, 10)), nil
	case WireArray:
		minimum := uint64(0)
		if field.MinItems != nil {
			minimum = *field.MinItems
		}
		if minimum == 0 {
			return nil, errors.New("array has no below-minimum value")
		}
		return arrayOfSizeJSONV1(field, minimum-1)
	}
	return nil, errors.New("descriptor has no below-minimum mutation")
}

func aboveMaximumJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	switch field.JSONType {
	case WireInteger:
		if field.MaxU64 == nil || *field.MaxU64 == ^uint64(0) {
			return nil, errors.New("integer has no above-maximum value")
		}
		return []byte(strconv.FormatUint(*field.MaxU64+1, 10)), nil
	case WireArray:
		if field.MaxItems == nil {
			return nil, errors.New("array has no maximum")
		}
		return arrayOfSizeJSONV1(field, *field.MaxItems+1)
	}
	return nil, errors.New("descriptor has no above-maximum mutation")
}

func oversizedJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	if field.JSONType != WireString || field.MaxBytes == nil {
		return nil, errors.New("descriptor has no string maximum")
	}
	length := *field.MaxBytes + 1
	switch field.ValueType {
	case "ed25519PublicKeyHex", "ed25519SignatureHex", "ledgerEventID":
		length = *field.MaxBytes + 2
	case "v4LedgerEventID":
		// The frozen negative is the retained 32-byte/64-character form,
		// not an odd-length syntactic hex string.
		length = 64
	}
	return json.Marshal(strings.Repeat("a", int(length)))
}

func arrayOfSizeJSONV1(field WireFieldDescriptorV1, count uint64) (json.RawMessage, error) {
	values := make([]json.RawMessage, 0, count)
	for index := uint64(0); index < count; index++ {
		value, err := minimalArrayElementJSONV1(field, arrayElementTypeV1(field.ValueType), index)
		if err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	return json.Marshal(values)
}

func mutateStringJSONV1(raw json.RawMessage, mutate func(string) string) (json.RawMessage, error) {
	var value string
	if json.Unmarshal(raw, &value) != nil {
		return nil, errors.New("mutation target is not a string")
	}
	return json.Marshal(mutate(value))
}

func uppercaseFirstAlphaV1(value string) string {
	data := []byte(value)
	for index, character := range data {
		if character >= 'a' && character <= 'f' {
			data[index] = character - ('a' - 'A')
			break
		}
	}
	return string(data)
}

func flipFirstHexV1(value string) string {
	if value == "" {
		return value
	}
	if value[0] == 'a' {
		return "b" + value[1:]
	}
	return "a" + value[1:]
}

func badCharacterJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	switch field.ValueType {
	case "path":
		return json.Marshal("/a")
	case "absPath":
		return json.Marshal("a")
	case "authorityDomain":
		return json.Marshal("a/b")
	default:
		if isHexWireType(field.ValueType) {
			length := 64
			if field.MinBytes != nil {
				length = int(*field.MinBytes)
			}
			return json.Marshal("g" + strings.Repeat("a", length-1))
		}
	}
	return nil, errors.New("descriptor has no BAD_CHAR mutation")
}

func unsortedArrayJSONV1(field WireFieldDescriptorV1, raw json.RawMessage) (json.RawMessage, error) {
	var values []json.RawMessage
	if json.Unmarshal(raw, &values) != nil {
		return nil, errors.New("mutation target is not an array")
	}
	if len(values) < 2 {
		var err error
		valuesRaw, err := arrayOfSizeJSONV1(field, 2)
		if err != nil {
			return nil, err
		}
		if json.Unmarshal(valuesRaw, &values) != nil {
			return nil, errors.New("cannot grow set for unsorted mutation")
		}
	}
	values[0], values[1] = values[1], values[0]
	return json.Marshal(values)
}

func duplicateArrayMemberJSONV1(field WireFieldDescriptorV1, raw json.RawMessage) (json.RawMessage, error) {
	var values []json.RawMessage
	if json.Unmarshal(raw, &values) != nil {
		return nil, errors.New("mutation target is not an array")
	}
	if len(values) == 0 {
		value, err := minimalArrayElementJSONV1(field, arrayElementTypeV1(field.ValueType), 0)
		if err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	values = append(values, append(json.RawMessage(nil), values[0]...))
	sort.Slice(values, func(i, j int) bool { return bytes.Compare(values[i], values[j]) < 0 })
	return json.Marshal(values)
}

func scalarForDescriptorV1(field WireFieldDescriptorV1, value string) (json.RawMessage, error) {
	switch field.JSONType {
	case WireBoolean, WireInteger, WireArray:
		return []byte(value), nil
	default:
		return json.Marshal(value)
	}
}

func mutatePredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, values map[string]json.RawMessage) error {
	fields := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		fields[field.FieldPath] = field
	}
	paths := predicate.FieldPaths
	if len(paths) == 0 || paths[0] == "$" {
		return fmt.Errorf("predicate %s has no executable field operands", predicate.PredicateID)
	}
	switch predicate.Operator {
	case PredicateExactLiteral:
		field := fields[paths[0]]
		changed, err := ConstantChangedV1(field)
		if err != nil {
			return err
		}
		values[paths[0]], err = scalarForDescriptorV1(field, changed)
		return err
	case PredicateAllEqual:
		if len(paths) < 2 {
			return errors.New("ALL_EQUAL requires two operands")
		}
		field := fields[paths[1]]
		changed, err := primitiveValidChangeV1(field, values[paths[1]])
		if err != nil {
			return err
		}
		values[paths[1]] = changed
	case PredicateExactlyOne:
		for _, path := range paths {
			if _, present := values[path]; !present {
				value, err := minimalDescriptorJSON(fields[path])
				if err != nil {
					return err
				}
				values[path] = value
				return nil
			}
		}
		delete(values, paths[len(paths)-1])
	case PredicateOrdinalSuccess:
		paths = integerPredicatePathsV1(paths, fields)
		if len(paths) < 2 {
			return errors.New("ORDINAL_SUCCESSOR requires two operands")
		}
		var predecessor uint64
		if json.Unmarshal(values[paths[0]], &predecessor) != nil {
			return errors.New("ordinal predecessor is invalid")
		}
		values[paths[1]] = []byte(strconv.FormatUint(predecessor+2, 10))
	case PredicateSubset:
		if len(paths) < 2 {
			return errors.New("SUBSET requires two operands")
		}
		field := fields[paths[0]]
		candidate, err := minimalArrayElementJSONV1(field, arrayElementTypeV1(field.ValueType), 1)
		if err != nil {
			return err
		}
		values[paths[0]], _ = json.Marshal([]json.RawMessage{candidate})
		values[paths[1]] = []byte("[]")
	case PredicateDigestPreimage:
		field := fields[paths[0]]
		values[paths[0]], _ = mutateStringJSONV1(values[paths[0]], flipFirstHexV1)
		_ = field
	case PredicateTypedReference, PredicateDerivation, PredicateStateTransition:
		field := fields[paths[0]]
		if _, present := values[paths[0]]; !present {
			var err error
			values[paths[0]], err = minimalDescriptorJSON(field)
			if err != nil {
				return err
			}
		}
		changed, err := primitiveValidChangeV1(field, values[paths[0]])
		if err != nil {
			return err
		}
		values[paths[0]] = changed
	case PredicateIfAndOnlyIf, PredicateImplies:
		if len(paths) < 2 {
			return errors.New("implication requires antecedent and consequent")
		}
		values[paths[0]] = []byte("true")
		values[paths[1]] = []byte("false")
	case PredicateAggregateLEQ:
		if len(paths) < 2 {
			return errors.New("aggregate requires addend and limit")
		}
		var limit uint64
		if json.Unmarshal(values[paths[len(paths)-1]], &limit) != nil {
			return errors.New("aggregate limit is invalid")
		}
		values[paths[0]] = []byte(strconv.FormatUint(limit+1, 10))
	default:
		return errors.New("predicate operator is not executable")
	}
	return nil
}

func primitiveValidChangeV1(field WireFieldDescriptorV1, raw json.RawMessage) (json.RawMessage, error) {
	switch field.JSONType {
	case WireString:
		var value string
		if json.Unmarshal(raw, &value) != nil {
			return nil, errors.New("string operand is invalid")
		}
		if isHexWireType(field.ValueType) {
			return json.Marshal(flipFirstHexV1(value))
		}
		for index := len(value) - 1; index >= 0; index-- {
			for _, replacement := range []byte{'a', 'b', '0', '1', '-', '_'} {
				if value[index] == replacement {
					continue
				}
				candidate := value[:index] + string(replacement) + value[index+1:]
				if ValidatePrimitiveWireValueV1(field.ValueType, candidate) == nil {
					return json.Marshal(candidate)
				}
			}
		}
	case WireInteger:
		var value uint64
		if json.Unmarshal(raw, &value) == nil && (field.MaxU64 == nil || value < *field.MaxU64) {
			return []byte(strconv.FormatUint(value+1, 10)), nil
		}
	case WireBoolean:
		var value bool
		if json.Unmarshal(raw, &value) == nil {
			return []byte(strconv.FormatBool(!value)), nil
		}
	}
	return nil, errors.New("operand has no primitive-valid change")
}

func resealDependentDigestsV1(entry CanonicalVectorEntryV1, values map[string]json.RawMessage, changed []string) ([]byte, error) {
	changedSet := make(map[string]struct{}, len(changed))
	for _, path := range changed {
		changedSet[path] = struct{}{}
	}
	for fieldIndex, field := range entry.Fields {
		if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, fieldIndex) {
			continue
		}
		if _, directlyChanged := changedSet[field.FieldPath]; directlyChanged {
			continue
		}
		preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
		if err != nil {
			return nil, err
		}
		values[field.FieldPath], _ = json.Marshal(sha256Hex(preimage))
	}
	return marshalCanonicalVectorObjectV1(entry.Fields, values, "")
}

// VerifyEd25519CanonicalVectorV1 proves the frozen wire widths and signature
// against the same message bytes used by positive generation.
func VerifyEd25519CanonicalVectorV1(publicKeyHex, signatureHex string, message []byte) error {
	publicKey, err := hex.DecodeString(publicKeyHex)
	if err != nil || len(publicKey) != ed25519.PublicKeySize {
		return errors.New("Ed25519 public key must be exactly 32 raw bytes")
	}
	signature, err := hex.DecodeString(signatureHex)
	if err != nil || len(signature) != ed25519.SignatureSize {
		return errors.New("Ed25519 signature must be exactly 64 raw bytes")
	}
	if publicKeyHex != strings.ToLower(publicKeyHex) || signatureHex != strings.ToLower(signatureHex) {
		return errors.New("Ed25519 wire must be lower-hex")
	}
	if !ed25519.Verify(ed25519.PublicKey(publicKey), message, signature) {
		return errors.New("Ed25519 signature verification failed")
	}
	return nil
}
