package governance

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

// ExecutableCanonicalVectorV1 is a generated byte vector, not a metadata
// recipe. FalsePredicateIDs is populated for predicate-negative vectors.
type ExecutableCanonicalVectorV1 struct {
	VectorID          string
	Bytes             []byte
	RequiredError     CanonicalRequiredError
	FalsePredicateIDs []string
}

type ExecutableCanonicalVectorSetV1 struct {
	SchemaID   string
	Positive   []byte
	Rejections []ExecutableCanonicalVectorV1
}

// GenerateCanonicalCatalogPositiveVectorsV1 materializes the complete frozen
// positive corpus. Record-valued fields and arrays are resolved recursively,
// so the result never substitutes an empty object for a required record.
func GenerateCanonicalCatalogPositiveVectorsV1(catalog CanonicalVectorCatalogV1) (map[string][]byte, error) {
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	byRecord := make(map[string]CanonicalVectorEntryV1, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		if prior, duplicate := byRecord[entry.RecordName]; duplicate && prior.SchemaID != entry.SchemaID {
			return nil, fmt.Errorf("record target %s is ambiguous", entry.RecordName)
		}
		byRecord[entry.RecordName] = entry
	}
	result := make(map[string][]byte, len(catalog.Entries))
	visiting := make(map[string]bool)
	var generate func(CanonicalVectorEntryV1) ([]byte, error)
	generate = func(entry CanonicalVectorEntryV1) ([]byte, error) {
		if positive, ok := result[entry.SchemaID]; ok {
			return append([]byte(nil), positive...), nil
		}
		if visiting[entry.SchemaID] {
			return nil, fmt.Errorf("required record target cycle at %s", entry.SchemaID)
		}
		visiting[entry.SchemaID] = true
		defer delete(visiting, entry.SchemaID)
		positive, err := GenerateMinimalCanonicalVectorV1(entry)
		if err != nil {
			return nil, err
		}
		if entry.RecordName == "ArtifactBlobV1" && entry.SchemaID == "artifact-blob-v1" {
			result[entry.SchemaID] = append([]byte(nil), positive...)
			return positive, nil
		}
		values, _, _, err := decodeCanonicalVectorObjectV1(positive)
		if err != nil {
			return nil, err
		}
		for _, field := range entry.Fields {
			raw, present := values[field.FieldPath]
			if !present {
				continue
			}
			switch field.JSONType {
			case WireObject:
				target, ok := byRecord[field.RecordTarget]
				if !ok {
					// Retained predecessor records are validated by their frozen V1
					// constructors and are not duplicated in the V4 catalog.
					continue
				}
				values[field.FieldPath], err = generate(target)
			case WireArray:
				targetName := field.RecordTarget
				if targetName == "" {
					elementType := arrayElementTypeV1(field.ValueType)
					if target, ok := byRecord[elementType]; ok {
						targetName = target.RecordName
					}
				}
				if targetName == "" {
					continue
				}
				target, ok := byRecord[targetName]
				if !ok {
					continue
				}
				var elements []json.RawMessage
				if json.Unmarshal(raw, &elements) != nil {
					return nil, fmt.Errorf("%s.%s positive is not an array", entry.SchemaID, field.FieldPath)
				}
				for index := range elements {
					elements[index], err = generate(target)
					if err != nil {
						break
					}
				}
				if err == nil {
					values[field.FieldPath], err = json.Marshal(elements)
				}
			}
			if err != nil {
				return nil, err
			}
		}
		if err := applyPositivePredicatesV1(entry, values); err != nil {
			return nil, err
		}
		if err := applyEd25519VectorsV1(entry, values); err != nil {
			return nil, err
		}
		for index, field := range entry.Fields {
			if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, index) {
				continue
			}
			preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
			if err != nil {
				return nil, err
			}
			values[field.FieldPath], _ = json.Marshal(sha256Hex(preimage))
		}
		positive, err = marshalCanonicalVectorObjectV1(entry.Fields, values, "")
		if err != nil {
			return nil, err
		}
		result[entry.SchemaID] = append([]byte(nil), positive...)
		return positive, nil
	}
	for _, entry := range catalog.Entries {
		if _, err := generate(entry); err != nil {
			return nil, err
		}
	}
	for _, entry := range catalog.Entries {
		if err := validateCanonicalCatalogPositiveV1(entry, result[entry.SchemaID], byRecord, make(map[string]bool)); err != nil {
			return nil, fmt.Errorf("validate %s positive: %w", entry.SchemaID, err)
		}
	}
	return result, nil
}

func validateCanonicalCatalogPositiveV1(entry CanonicalVectorEntryV1, data []byte, byRecord map[string]CanonicalVectorEntryV1, visiting map[string]bool) error {
	if err := validateCanonicalVectorBytesV1(entry, data); err != nil {
		return err
	}
	if entry.RecordName == "ArtifactBlobV1" {
		return nil
	}
	if visiting[entry.SchemaID] {
		return errors.New("record target cycle")
	}
	visiting[entry.SchemaID] = true
	defer delete(visiting, entry.SchemaID)
	values, _, _, err := decodeCanonicalVectorObjectV1(data)
	if err != nil {
		return err
	}
	for _, field := range entry.Fields {
		raw, present := values[field.FieldPath]
		if !present {
			continue
		}
		targetName := field.RecordTarget
		if targetName == "" && field.JSONType == WireArray {
			targetName = arrayElementTypeV1(field.ValueType)
		}
		target, ok := byRecord[targetName]
		if !ok {
			continue
		}
		if field.JSONType == WireObject {
			if err := validateCanonicalCatalogPositiveV1(target, raw, byRecord, visiting); err != nil {
				return fmt.Errorf("field %s: %w", field.FieldPath, err)
			}
		}
		if field.JSONType == WireArray {
			var elements []json.RawMessage
			if json.Unmarshal(raw, &elements) != nil {
				return fmt.Errorf("field %s is not an array", field.FieldPath)
			}
			for index, element := range elements {
				if err := validateCanonicalCatalogPositiveV1(target, element, byRecord, visiting); err != nil {
					return fmt.Errorf("field %s[%d]: %w", field.FieldPath, index, err)
				}
			}
		}
	}
	return nil
}

type canonicalVectorValidationErrorV1 struct {
	code            CanonicalRequiredError
	path            string
	falsePredicates []string
}

func (e *canonicalVectorValidationErrorV1) Error() string {
	if len(e.falsePredicates) != 0 {
		return fmt.Sprintf("%s: predicates %s", e.code, strings.Join(e.falsePredicates, ","))
	}
	if e.path != "" {
		return fmt.Sprintf("%s: field %s", e.code, e.path)
	}
	return string(e.code)
}

// ValidateCanonicalVectorBytesV1 mechanically validates one record against
// the extracted descriptors and complete frozen predicate set. It is also used
// by generation, so a recipe can never be reported as an executable vector
// unless its bytes actually produce the frozen result class.
func ValidateCanonicalVectorBytesV1(entry CanonicalVectorEntryV1, data []byte) error {
	return validateCanonicalVectorBytesV1(entry, data)
}

// GenerateExecutableCanonicalVectorsV1 materializes and validates the
// positive vector and every rejection recipe carried by an entry.
func GenerateExecutableCanonicalVectorsV1(entry CanonicalVectorEntryV1) (ExecutableCanonicalVectorSetV1, error) {
	positive, err := GenerateMinimalCanonicalVectorV1(entry)
	if err != nil {
		return ExecutableCanonicalVectorSetV1{}, err
	}
	return generateExecutableCanonicalVectorsFromPositiveV1(entry, positive)
}

// GenerateExecutableCanonicalCatalogVectorsV1 materializes the complete
// frozen catalog. Every rejection starts from the recursively materialized
// positive for that exact entry, including record-valued fields and record
// array elements; the descriptor-only minimal object is never used as a
// rejection base for this path.
func GenerateExecutableCanonicalCatalogVectorsV1(catalog CanonicalVectorCatalogV1) (map[string]ExecutableCanonicalVectorSetV1, error) {
	positives, err := GenerateCanonicalCatalogPositiveVectorsV1(catalog)
	if err != nil {
		return nil, err
	}
	result := make(map[string]ExecutableCanonicalVectorSetV1, len(catalog.Entries))
	positiveByRecord := make(map[string][]byte, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		positiveByRecord[entry.RecordName] = positives[entry.SchemaID]
	}
	for _, entry := range catalog.Entries {
		vectors, err := generateExecutableCanonicalVectorsFromPositiveV1(entry, positives[entry.SchemaID], positiveByRecord)
		if err != nil {
			return nil, fmt.Errorf("materialize %s executable vectors: %w", entry.SchemaID, err)
		}
		result[entry.SchemaID] = vectors
	}
	return result, nil
}

func generateExecutableCanonicalVectorsFromPositiveV1(entry CanonicalVectorEntryV1, positive []byte, positiveByRecord ...map[string][]byte) (ExecutableCanonicalVectorSetV1, error) {
	var recordPositives map[string][]byte
	if len(positiveByRecord) != 0 {
		recordPositives = positiveByRecord[0]
	}
	if err := validateCanonicalVectorBytesV1(entry, positive); err != nil {
		return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("positive vector for %s is invalid: %w", entry.SchemaID, err)
	}
	result := ExecutableCanonicalVectorSetV1{SchemaID: entry.SchemaID, Positive: append([]byte(nil), positive...), Rejections: make([]ExecutableCanonicalVectorV1, 0, len(entry.Rejections))}
	for _, recipe := range entry.Rejections {
		mutated, err := mutateCanonicalVectorV1(entry, positive, recipe, recordPositives)
		if err != nil {
			return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("generate %s: %w", recipe.VectorID, err)
		}
		if strings.Contains(recipe.Mutation, "PREDICATE_") {
			if recipe.RequiredError != CanonicalPredicateInvalid {
				return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("vector %s has predicate mutation with error class %s", recipe.VectorID, recipe.RequiredError)
			}
			_, descriptorErr := validateCanonicalVectorDescriptorConstraintsV1(entry, mutated)
			if descriptorErr != nil {
				predicateID := strings.TrimPrefix(recipe.Mutation, "PREDICATE_")
				predicate, _ := canonicalVectorPredicateV1(entry.Predicates, predicateID)
				return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("vector %s (%s paths=%v arguments=%v) violates a descriptor constraint: %w", recipe.VectorID, predicate.Operator, predicate.FieldPaths, predicate.Arguments, descriptorErr)
			}
			target := strings.TrimPrefix(recipe.Mutation, "PREDICATE_")
			falseIDs, err := falseCanonicalPredicatesForMutationV1(entry, positive, mutated, target)
			if err != nil {
				return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("vector %s does not prove its expected predicate classification: %w", recipe.VectorID, err)
			}
			result.Rejections = append(result.Rejections, ExecutableCanonicalVectorV1{
				VectorID: recipe.VectorID, Bytes: mutated, RequiredError: recipe.RequiredError, FalsePredicateIDs: falseIDs,
			})
			continue
		}
		validationErr := validateCanonicalVectorBytesV1(entry, mutated)
		var classified *canonicalVectorValidationErrorV1
		if !errors.As(validationErr, &classified) || classified.code != recipe.RequiredError {
			return ExecutableCanonicalVectorSetV1{}, fmt.Errorf("vector %s classified as %v, want %s", recipe.VectorID, validationErr, recipe.RequiredError)
		}
		falseIDs := append([]string(nil), classified.falsePredicates...)
		sort.Strings(falseIDs)
		result.Rejections = append(result.Rejections, ExecutableCanonicalVectorV1{
			VectorID: recipe.VectorID, Bytes: mutated, RequiredError: recipe.RequiredError, FalsePredicateIDs: falseIDs,
		})
	}
	return result, nil
}

func falseCanonicalPredicatesForMutationV1(entry CanonicalVectorEntryV1, positive, mutated []byte, target string) ([]string, error) {
	if err := validateCanonicalVectorBytesV1(entry, positive); err != nil {
		return nil, fmt.Errorf("positive validation: %w", err)
	}
	mutatedValues, err := validateCanonicalVectorDescriptorConstraintsV1(entry, mutated)
	if err != nil {
		return nil, fmt.Errorf("mutated descriptor validation: %w", err)
	}
	falseIDs := falseCanonicalPredicatesV1(entry, mutatedValues)
	if _, found := canonicalVectorPredicateV1(entry.Predicates, target); !found {
		return nil, fmt.Errorf("target predicate %s is absent", target)
	}
	if !containsCanonicalVectorStringV1(falseIDs, target) {
		predicate, _ := canonicalVectorPredicateV1(entry.Predicates, target)
		return nil, fmt.Errorf("target predicate %s (%s paths=%v arguments=%v) remained true", target, predicate.Operator, predicate.FieldPaths, predicate.Arguments)
	}
	validationErr := validateCanonicalVectorBytesV1(entry, mutated)
	var classified *canonicalVectorValidationErrorV1
	if !errors.As(validationErr, &classified) || classified.code != CanonicalPredicateInvalid {
		return nil, fmt.Errorf("mutation classified as %v, want %s", validationErr, CanonicalPredicateInvalid)
	}
	actual := append([]string(nil), classified.falsePredicates...)
	sort.Strings(actual)
	if !equalVectorStringsV1(actual, falseIDs) {
		return nil, fmt.Errorf("validator false predicates %v, evaluator produced %v", actual, falseIDs)
	}
	return falseIDs, nil
}

func validateCanonicalVectorBytesV1(entry CanonicalVectorEntryV1, data []byte) error {
	if entry.RecordName == "ArtifactBlobV1" && entry.SchemaID == "artifact-blob-v1" {
		if len(data) >= 1 && len(data) <= 33554432 {
			return nil
		}
		return &canonicalVectorValidationErrorV1{code: CanonicalBoundInvalid}
	}
	if !utf8.Valid(data) || len(data) == 0 || len(data) > 1<<20 {
		return &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	values, err := validateCanonicalVectorDescriptorConstraintsV1(entry, data)
	if err != nil {
		return err
	}
	falsePredicates := falseCanonicalPredicatesV1(entry, values)
	for fieldIndex, field := range entry.Fields {
		if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, fieldIndex) {
			continue
		}
		var actual string
		if json.Unmarshal(values[field.FieldPath], &actual) != nil {
			return &canonicalVectorValidationErrorV1{code: CanonicalTypeInvalid, path: field.FieldPath}
		}
		preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
		if err != nil || actual != sha256Hex(preimage) {
			if len(falsePredicates) != 0 {
				return &canonicalVectorValidationErrorV1{code: CanonicalPredicateInvalid, falsePredicates: falsePredicates}
			}
			return &canonicalVectorValidationErrorV1{code: CanonicalDigestInvalid, path: field.FieldPath}
		}
	}
	if len(falsePredicates) != 0 {
		return &canonicalVectorValidationErrorV1{code: CanonicalPredicateInvalid, falsePredicates: falsePredicates}
	}
	return nil
}

func validateCanonicalVectorDescriptorConstraintsV1(entry CanonicalVectorEntryV1, data []byte) (map[string]json.RawMessage, error) {
	values, order, duplicate, parseErr := decodeCanonicalVectorObjectV1(data)
	if parseErr != nil {
		return nil, &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	if duplicate {
		return nil, &canonicalVectorValidationErrorV1{code: CanonicalDuplicateField}
	}
	descriptors := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		descriptors[field.FieldPath] = field
	}
	for _, name := range order {
		if _, ok := descriptors[name]; !ok {
			return nil, &canonicalVectorValidationErrorV1{code: CanonicalUnknownField}
		}
	}
	expectedOrder := make([]string, 0, len(entry.Fields))
	for _, field := range entry.Fields {
		_, present := values[field.FieldPath]
		if !present && !field.Optional {
			return nil, &canonicalVectorValidationErrorV1{code: CanonicalMissingField}
		}
		if present {
			expectedOrder = append(expectedOrder, field.FieldPath)
		}
	}
	if !equalVectorStringsV1(order, expectedOrder) {
		return nil, &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	canonical, err := marshalCanonicalVectorObjectV1(entry.Fields, values, "")
	if err != nil || !bytes.Equal(canonical, data) {
		return nil, &canonicalVectorValidationErrorV1{code: CanonicalNonCanonical}
	}
	for _, field := range entry.Fields {
		raw, present := values[field.FieldPath]
		if !present {
			continue
		}
		if code := validateCanonicalDescriptorValueV1(field, raw); code != "" {
			return nil, &canonicalVectorValidationErrorV1{code: code, path: field.FieldPath}
		}
	}
	return values, nil
}

func equalVectorStringsV1(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func decodeCanonicalVectorObjectV1(data []byte) (map[string]json.RawMessage, []string, bool, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	token, err := decoder.Token()
	if err != nil || token != json.Delim('{') {
		return nil, nil, false, errors.New("record is not an object")
	}
	values := make(map[string]json.RawMessage)
	var order []string
	duplicate := false
	for decoder.More() {
		nameToken, err := decoder.Token()
		if err != nil {
			return nil, nil, false, err
		}
		name, ok := nameToken.(string)
		if !ok {
			return nil, nil, false, errors.New("field name is not a string")
		}
		var raw json.RawMessage
		if err := decoder.Decode(&raw); err != nil {
			return nil, nil, false, err
		}
		if _, exists := values[name]; exists {
			duplicate = true
		}
		values[name] = append(json.RawMessage(nil), raw...)
		order = append(order, name)
	}
	if token, err = decoder.Token(); err != nil || token != json.Delim('}') {
		return nil, nil, false, errors.New("record is unterminated")
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, nil, false, errors.New("record has trailing JSON")
	}
	return values, order, duplicate, nil
}

func validateCanonicalDescriptorValueV1(field WireFieldDescriptorV1, raw json.RawMessage) CanonicalRequiredError {
	if bytes.Equal(raw, []byte("null")) {
		return CanonicalTypeInvalid
	}
	switch field.JSONType {
	case WireString:
		var value string
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinBytes != nil && uint64(len(value)) < *field.MinBytes || field.MaxBytes != nil && uint64(len(value)) > *field.MaxBytes {
			return CanonicalBoundInvalid
		}
		if isClosedEnumType(field.ValueType) || strings.HasPrefix(field.ValueType, "{") {
			if err := ValidatePrimitiveWireValueV1(field.ValueType, value); err != nil {
				return CanonicalEnumInvalid
			}
		}
		var primitiveErr error
		if strings.HasPrefix(field.ValueType, "sha256<") || field.ValueType == "blob256" {
			primitiveErr = validateExactLowerHex(value, 64)
		} else {
			primitiveErr = ValidatePrimitiveWireValueV1(field.ValueType, value)
		}
		if primitiveErr != nil {
			if field.ValueType == "absPath" && strings.HasPrefix(value, "/") && strings.Contains(value, "/../") {
				return CanonicalNonCanonical
			}
			return CanonicalBoundInvalid
		}
	case WireInteger:
		var value uint64
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinU64 != nil && value < *field.MinU64 || field.MaxU64 != nil && value > *field.MaxU64 {
			return CanonicalBoundInvalid
		}
	case WireBoolean:
		var value bool
		if json.Unmarshal(raw, &value) != nil {
			return CanonicalTypeInvalid
		}
	case WireArray:
		var values []json.RawMessage
		if json.Unmarshal(raw, &values) != nil {
			return CanonicalTypeInvalid
		}
		if field.MinItems != nil && uint64(len(values)) < *field.MinItems || field.MaxItems != nil && uint64(len(values)) > *field.MaxItems {
			return CanonicalBoundInvalid
		}
		if strings.Contains(field.ValueType, "(set") {
			for index := 1; index < len(values); index++ {
				comparison := bytes.Compare(values[index-1], values[index])
				if comparison >= 0 {
					return CanonicalOrderInvalid
				}
			}
		}
		elementType := arrayElementTypeV1(field.ValueType)
		if elementType != "" && !(strings.HasSuffix(elementType, "V1") || strings.HasSuffix(elementType, "V2") || strings.HasSuffix(elementType, "V3") || strings.HasSuffix(elementType, "V4")) {
			descriptor, err := ResolveWireFieldDescriptorV1(field.SchemaID, field.FieldPath, field.Ordinal, elementType, false)
			if err != nil {
				return CanonicalTypeInvalid
			}
			for _, value := range values {
				if code := validateCanonicalDescriptorValueV1(descriptor, value); code != "" {
					return code
				}
			}
		}
	case WireObject:
		if len(raw) == 0 || raw[0] != '{' || !json.Valid(raw) {
			return CanonicalTypeInvalid
		}
	case WireRawJSON:
		if !json.Valid(raw) || len(raw) == 0 || raw[0] != '{' && raw[0] != '[' {
			return CanonicalTypeInvalid
		}
		if field.MinBytes != nil && uint64(len(raw)) < *field.MinBytes || field.MaxBytes != nil && uint64(len(raw)) > *field.MaxBytes {
			return CanonicalBoundInvalid
		}
	default:
		return CanonicalTypeInvalid
	}
	return ""
}

func sha256Hex(data []byte) string {
	digest := sha256.Sum256(data)
	return hex.EncodeToString(digest[:])
}

func falseCanonicalPredicatesV1(entry CanonicalVectorEntryV1, values map[string]json.RawMessage) []string {
	fields := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		fields[field.FieldPath] = field
	}
	expected := minimalCanonicalPredicateValuesV1(entry)
	var result []string
	for _, predicate := range entry.Predicates {
		if !canonicalPredicateValidV1(entry, predicate, fields, values, expected) {
			result = append(result, predicate.PredicateID)
		}
	}
	sort.Strings(result)
	return result
}

func minimalCanonicalPredicateValuesV1(entry CanonicalVectorEntryV1) map[string]json.RawMessage {
	positive, err := GenerateMinimalCanonicalVectorV1(entry)
	if err != nil {
		return nil
	}
	values, _, _, err := decodeCanonicalVectorObjectV1(positive)
	if err != nil {
		return nil
	}
	return values
}

func canonicalPredicateValidV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, fields map[string]WireFieldDescriptorV1, values, expected map[string]json.RawMessage) bool {
	paths := canonicalPredicateOperandPathsV1(entry, predicate, fields)
	switch predicate.Operator {
	case PredicateExactLiteral:
		if len(predicate.FieldPaths) != 1 || len(predicate.Arguments) == 0 {
			return false
		}
		raw, present := values[predicate.FieldPaths[0]]
		field, found := fields[predicate.FieldPaths[0]]
		if !present || !found {
			return false
		}
		switch field.JSONType {
		case WireString:
			var scalar string
			return json.Unmarshal(raw, &scalar) == nil && scalar == predicate.Arguments[0]
		case WireInteger, WireBoolean, WireArray:
			return string(raw) == predicate.Arguments[0]
		default:
			return false
		}
	case PredicateAllEqual:
		if len(paths) == 1 {
			actual, present := values[paths[0]]
			want, expectedPresent := expected[paths[0]]
			return present == expectedPresent && (!present || bytes.Equal(actual, want))
		}
		if len(paths) < 2 {
			return false
		}
		first, present := values[paths[0]]
		if !present {
			return false
		}
		for _, path := range paths[1:] {
			if next, ok := values[path]; !ok || !bytes.Equal(first, next) {
				return false
			}
		}
		return true
	case PredicateIfAndOnlyIf, PredicateImplies:
		if valid, handled := frozenImplicationPredicateV1(entry, predicate, values); handled {
			return valid
		}
		if len(paths) < 2 {
			return false
		}
		antecedent := canonicalPredicateConditionV1(paths[0], fields, values, expected)
		consequent := canonicalPredicateConditionV1(paths[1], fields, values, expected)
		if predicate.Operator == PredicateIfAndOnlyIf {
			return antecedent == consequent
		}
		return !antecedent || consequent
	case PredicateExactlyOne:
		count := 0
		for _, path := range paths {
			if _, present := values[path]; present {
				count++
			}
		}
		return count == 1
	case PredicateSubset:
		if len(paths) < 2 {
			return false
		}
		var subset, superset []json.RawMessage
		if json.Unmarshal(values[paths[0]], &subset) != nil || json.Unmarshal(values[paths[1]], &superset) != nil {
			return false
		}
		members := make(map[string]struct{}, len(superset))
		for _, value := range superset {
			members[string(value)] = struct{}{}
		}
		for _, value := range subset {
			if _, found := members[string(value)]; !found {
				return false
			}
		}
		return true
	case PredicateOrdinalSuccess:
		if len(paths) == 1 {
			actual, present := values[paths[0]]
			want, expectedPresent := expected[paths[0]]
			return present == expectedPresent && (!present || bytes.Equal(actual, want))
		}
		if len(paths) < 2 {
			return false
		}
		var predecessor, successor uint64
		return json.Unmarshal(values[paths[0]], &predecessor) == nil && json.Unmarshal(values[paths[1]], &successor) == nil && predecessor != ^uint64(0) && successor == predecessor+1
	case PredicateStateTransition:
		return frozenStatePredicateV1(entry, predicate, paths, values, expected)
	case PredicateTypedReference:
		if len(paths) == 0 {
			return false
		}
		for _, path := range paths {
			actual, present := values[path]
			field := fields[path]
			if present && field.DigestTarget != "" {
				for _, candidate := range entry.Fields {
					if candidate.JSONType != WireObject || candidate.RecordTarget != field.DigestTarget {
						continue
					}
					var digest string
					if embedded, ok := values[candidate.FieldPath]; ok && json.Unmarshal(actual, &digest) == nil && digest == sha256Hex(embedded) {
						present = false
						break
					}
				}
				if !present {
					continue
				}
			}
			want, expectedPresent := expected[path]
			if present != expectedPresent || present && !bytes.Equal(actual, want) {
				return false
			}
		}
		return true
	case PredicateDigestPreimage:
		return frozenDigestPreimagePredicateV1(entry, predicate, values, expected)
	case PredicateDerivation:
		path := canonicalDerivedOutputPathV1(entry, predicate, fields)
		actual, present := values[path]
		want, expectedPresent := expected[path]
		return path != "" && present == expectedPresent && (!present || bytes.Equal(actual, want))
	case PredicateAggregateLEQ:
		if len(paths) < 2 {
			return false
		}
		var sum uint64
		for _, path := range paths[:len(paths)-1] {
			var addend uint64
			if json.Unmarshal(values[path], &addend) != nil || ^uint64(0)-sum < addend {
				return false
			}
			sum += addend
		}
		var limit uint64
		return json.Unmarshal(values[paths[len(paths)-1]], &limit) == nil && sum <= limit
	default:
		return false
	}
}

func canonicalPredicateConditionV1(path string, fields map[string]WireFieldDescriptorV1, values, expected map[string]json.RawMessage) bool {
	actual, present := values[path]
	want, expectedPresent := expected[path]
	if field, ok := fields[path]; ok && field.JSONType == WireBoolean && present {
		return bytes.Equal(actual, []byte("true"))
	}
	return present == expectedPresent && (!present || bytes.Equal(actual, want))
}

func frozenImplicationPredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, values map[string]json.RawMessage) (bool, bool) {
	stringValue := func(path string) string {
		var value string
		_ = json.Unmarshal(values[path], &value)
		return value
	}
	switch predicate.PredicateID {
	case "P-PUBLISHER-001":
		return stringValue("lifecycle") == "ACTIVE", true
	case "P-PUBLISHER-002":
		_, revision := values["terminal_revision"]
		operation := stringValue("terminal_operation")
		_, recovery := values["recovery_proof_sha256"]
		switch stringValue("lifecycle") {
		case "ACTIVE":
			return !revision && operation == "" && !recovery, true
		case "FINALIZED":
			return revision && operation == "FINALIZE" && !recovery, true
		case "ABANDONED":
			return revision && operation == "ABANDON" && recovery, true
		default:
			return false, true
		}
	case "P-SUBJECT-001":
		return bytes.Equal(values["candidate_oid"], values["diff_candidate_oid"]), true
	}
	return false, false
}

func frozenStatePredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, paths []string, values, expected map[string]json.RawMessage) bool {
	stringValue := func(path string) string {
		var value string
		_ = json.Unmarshal(values[path], &value)
		return value
	}
	switch predicate.PredicateID {
	case "P-BARRIER-001":
		var digest string
		return json.Unmarshal(values["commitment_sha256"], &digest) == nil && digest == sha256Hex(values["commitment"])
	case "P-EVENT-001":
		kind := stringValue("effect_kind")
		from, to, source := stringValue("state_from"), stringValue("state_to"), stringValue("source")
		if kind == "PR" {
			return from == "INTEGRATION_ACCEPTED" && to == "READY_FOR_MERGE" && source == "assurance-pr-effect-v4"
		}
		return kind == "MERGE" && from == "READY_FOR_MERGE" && to == "MERGED" && source == "assurance-merge-effect-v4"
	case "P-BARRIER-008":
		kind := stringValue("effect_kind")
		from, to := stringValue("source_state"), stringValue("applied_state_to")
		if kind == "PR" {
			return from == "INTEGRATION_ACCEPTED" && to == "READY_FOR_MERGE"
		}
		return kind == "MERGE" && from == "READY_FOR_MERGE" && to == "MERGED"
	case "P-PUBLISHER-006":
		assembled, err1 := time.Parse(time.RFC3339Nano, stringValue("proof_assembled_at"))
		validFrom, err2 := time.Parse(time.RFC3339Nano, stringValue("valid_from"))
		expires, err3 := time.Parse(time.RFC3339Nano, stringValue("expires_at"))
		return err1 == nil && err2 == nil && err3 == nil && !validFrom.Before(assembled) && expires.After(validFrom) && !expires.After(assembled.Add(30*time.Second))
	case "P-predecessor-writer-lease-v1-ROW-001":
		return stringValue("lease_state") == "ACTIVE"
	case "P-RESOURCE-002":
		_, released := values["released_at_revision"]
		_, evidence := values["release_evidence_sha256"]
		if stringValue("lifecycle") == "RELEASED" {
			return released && evidence
		}
		return !released && !evidence
	}
	if len(paths) >= 2 {
		edges := frozenTransitionEdgesV1(predicate)
		if len(edges) != 0 {
			return edges[stringValue(paths[0])+"\x00"+stringValue(paths[1])]
		}
	}
	path := canonicalStateDestinationPathV1(entry, predicate, paths)
	actual, present := values[path]
	want, expectedPresent := expected[path]
	return path != "" && present == expectedPresent && (!present || bytes.Equal(actual, want))
}

func frozenDigestPreimagePredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, values, expected map[string]json.RawMessage) bool {
	if len(predicate.FieldPaths) == 0 {
		return false
	}
	if predicate.PredicateID == "P-effect-ledger-event-preimage-v1-ROW-003" {
		var eventID string
		return json.Unmarshal(values["event_id"], &eventID) == nil && eventID == effectLedgerEventIDV1(entry, values)
	}
	path := predicate.FieldPaths[0]
	fieldIndex := -1
	for index, field := range entry.Fields {
		if field.FieldPath == path {
			fieldIndex = index
			break
		}
	}
	if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, fieldIndex) {
		fields := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
		for _, field := range entry.Fields {
			fields[field.FieldPath] = field
		}
		paths := canonicalPredicateOperandPathsV1(entry, predicate, fields)
		output := ""
		for _, candidate := range paths {
			field := fields[candidate]
			if field.DigestTarget != "" || strings.HasSuffix(candidate, "_sha256") || candidate == "event_id" {
				output = candidate
				break
			}
		}
		changed := false
		compared := 0
		for _, candidate := range paths {
			field := fields[candidate]
			if candidate == output || field.JSONType == WireObject || field.JSONType == WireArray {
				continue
			}
			compared++
			actual, present := values[candidate]
			want, expectedPresent := expected[candidate]
			changed = changed || present != expectedPresent || present && !bytes.Equal(actual, want)
		}
		if compared == 0 {
			for _, field := range entry.Fields {
				if field.FieldPath == output || field.DigestTarget != "" || field.JSONType == WireObject || field.JSONType == WireArray {
					continue
				}
				actual, present := values[field.FieldPath]
				want, expectedPresent := expected[field.FieldPath]
				changed = changed || present != expectedPresent || present && !bytes.Equal(actual, want)
			}
		}
		if !changed {
			return true
		}
		if output == "" {
			return false
		}
		// Retaining the frozen output while an actual preimage operand changes
		// is the deterministic DIGEST_PREIMAGE rejection. Directly replacing
		// the output is left to its typed-reference/digest classifier.
		return !bytes.Equal(values[output], expected[output])
	}
	var actual string
	if json.Unmarshal(values[path], &actual) != nil {
		return false
	}
	preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, path)
	if err == nil && actual == sha256Hex(preimage) {
		return true
	}
	// A predicate vector changes the preimage while deliberately retaining the
	// frozen positive digest. A direct digest mutation is classified by the
	// digest validator instead of being relabelled as a predicate failure.
	for _, field := range entry.Fields {
		if field.FieldPath == path || field.FieldPath == "event_id" || field.DigestTarget != "" || field.JSONType == WireObject || field.JSONType == WireArray {
			continue
		}
		value, present := values[field.FieldPath]
		want, expectedPresent := expected[field.FieldPath]
		if present != expectedPresent || present && !bytes.Equal(value, want) {
			return false
		}
	}
	return true
}

func effectLedgerEventIDV1(entry CanonicalVectorEntryV1, values map[string]json.RawMessage) string {
	selected := make([]WireFieldDescriptorV1, 0, len(entry.Fields))
	for _, field := range entry.Fields {
		if field.FieldPath == "event_id" {
			continue
		}
		selected = append(selected, field)
		if field.FieldPath == "evidence_refs" {
			break
		}
	}
	preimage, err := marshalCanonicalVectorObjectV1(selected, values, "")
	if err != nil {
		return ""
	}
	digest := sha256.Sum256(preimage)
	return hex.EncodeToString(digest[:16])
}

func mutateCanonicalVectorV1(entry CanonicalVectorEntryV1, positive []byte, recipe CanonicalRejectionVectorV1, positiveByRecord ...map[string][]byte) ([]byte, error) {
	var recordPositives map[string][]byte
	if len(positiveByRecord) != 0 {
		recordPositives = positiveByRecord[0]
	}
	if entry.RecordName == "ArtifactBlobV1" && entry.SchemaID == "artifact-blob-v1" {
		switch recipe.Mutation {
		case "BELOW_MIN":
			return []byte{}, nil
		case "ABOVE_MAX":
			return make([]byte, 33554433), nil
		default:
			return nil, fmt.Errorf("unsupported raw artifact mutation %s", recipe.Mutation)
		}
	}
	values, _, _, err := decodeCanonicalVectorObjectV1(positive)
	if err != nil {
		return nil, err
	}
	path, mutation := rejectionTargetAndMutationV1(entry.SchemaID, recipe.VectorID)
	if path == "$" {
		switch mutation {
		case "UNKNOWN_FIRST":
			return append([]byte(`{"__unknown":false,`), positive[1:]...), nil
		case "UNKNOWN_LAST":
			return append(append([]byte(nil), positive[:len(positive)-1]...), []byte(`,"__unknown":false}`)...), nil
		case "DUPLICATE_FIELD":
			if len(entry.Fields) == 0 {
				return nil, errors.New("record has no duplicable field")
			}
			field := entry.Fields[0]
			value, ok := values[field.FieldPath]
			if !ok {
				return nil, errors.New("first field is absent")
			}
			name, _ := json.Marshal(field.FieldPath)
			prefix := append(append(append([]byte{'{'}, name...), ':'), value...)
			prefix = append(prefix, ',')
			return append(prefix, positive[1:]...), nil
		case "INVALID_UTF8":
			result := append([]byte(nil), positive...)
			for index := 1; index < len(result)-1; index++ {
				if result[index] == 'a' {
					result[index] = 0xff
					return result, nil
				}
			}
			return append(result[:len(result)-1], []byte(",\"x\":\"\xff\"}")...), nil
		case "TRAILING_JSON":
			return append(append([]byte(nil), positive...), []byte("{}")...), nil
		}
	}
	if strings.HasPrefix(mutation, "PREDICATE_") {
		predicateID := strings.TrimPrefix(mutation, "PREDICATE_")
		predicate, found := canonicalVectorPredicateV1(entry.Predicates, predicateID)
		if !found {
			return nil, fmt.Errorf("unknown predicate %s", predicateID)
		}
		if err := mutatePredicateV1(entry, predicate, values, recordPositives); err != nil {
			return nil, fmt.Errorf("mutate %s paths=%v arguments=%v: %w", predicate.Operator, predicate.FieldPaths, predicate.Arguments, err)
		}
		changedPaths := append([]string(nil), predicate.FieldPaths...)
		if predicate.Operator == PredicateDigestPreimage {
			for index, field := range entry.Fields {
				if isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, index) {
					changedPaths = append(changedPaths, field.FieldPath)
				}
			}
		}
		return resealDependentDigestsV1(entry, values, changedPaths)
	}
	field, ok := canonicalVectorFieldV1(entry.Fields, path)
	if !ok {
		return nil, fmt.Errorf("unknown mutation path %s", path)
	}
	if _, present := values[path]; !present {
		values[path], err = descriptorPositiveForMutationV1(field, recordPositives)
		if err != nil {
			return nil, fmt.Errorf("materialize optional mutation target %s: %w", path, err)
		}
	}
	switch mutation {
	case "REMOVE":
		delete(values, path)
	case "NULL":
		values[path] = []byte("null")
	case "WRONG_TYPE":
		values[path] = wrongJSONTypeV1(field.JSONType)
	case "BELOW_MIN":
		values[path], err = belowMinimumJSONV1(field, recordPositives)
	case "ABOVE_MAX":
		values[path], err = aboveMaximumJSONV1(field, recordPositives)
	case "OVERSIZE":
		values[path], err = oversizedJSONV1(field)
	case "ENUM_INVALID":
		values[path], err = invalidEnumJSONV1(field)
	case "UPPERCASE":
		values[path], err = mutateStringJSONV1(values[path], uppercaseFirstAlphaV1)
	case "SHORT":
		values[path], err = mutateStringJSONV1(values[path], func(value string) string {
			if len(value) >= 2 {
				return value[:len(value)-2]
			}
			return ""
		})
	case "BAD_CHAR":
		values[path], err = badCharacterJSONV1(field)
	case "UNSORTED":
		values[path], err = unsortedArrayJSONV1(field, values[path], recordPositives)
	case "DUPLICATE_MEMBER":
		values[path], err = duplicateArrayMemberJSONV1(field, values[path], recordPositives)
	case "CONSTANT_CHANGED":
		var changed string
		changed, err = ConstantChangedV1(field)
		if err == nil {
			values[path], err = scalarForDescriptorV1(field, changed)
		}
	case "SELF_DIGEST_MISMATCH":
		values[path], err = mutateStringJSONV1(values[path], flipFirstHexV1)
	default:
		return nil, fmt.Errorf("unsupported canonical mutation %s", mutation)
	}
	if err != nil {
		return nil, err
	}
	if mutation != "SELF_DIGEST_MISMATCH" {
		return resealDependentDigestsV1(entry, values, []string{path})
	}
	return marshalCanonicalVectorObjectV1(entry.Fields, values, "")
}

func descriptorPositiveForMutationV1(field WireFieldDescriptorV1, recordPositives map[string][]byte) (json.RawMessage, error) {
	switch field.JSONType {
	case WireObject:
		if positive := recordPositives[field.RecordTarget]; len(positive) != 0 {
			return append(json.RawMessage(nil), positive...), nil
		}
	case WireArray:
		minimum := uint64(0)
		if field.MinItems != nil {
			minimum = *field.MinItems
		}
		return arrayOfSizeJSONV1(field, minimum, recordPositives)
	}
	return minimalDescriptorJSON(field)
}

func invalidEnumJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	if field.JSONType != WireString || field.MinBytes == nil || field.MaxBytes == nil {
		return nil, errors.New("enum descriptor has no string bounds")
	}
	for length := *field.MinBytes; length <= *field.MaxBytes; length++ {
		for _, character := range []byte{'x', 'y', 'z'} {
			candidate := strings.Repeat(string(character), int(length))
			if ValidatePrimitiveWireValueV1(field.ValueType, candidate) != nil {
				return json.Marshal(candidate)
			}
		}
		if length == *field.MaxBytes {
			break
		}
	}
	return nil, errors.New("enum has no bounded invalid member")
}

func rejectionTargetAndMutationV1(schemaID, vectorID string) (string, string) {
	prefix := schemaID + "/"
	remaining := strings.TrimPrefix(vectorID, prefix)
	index := strings.LastIndexByte(remaining, '/')
	if index < 0 {
		return "$", remaining
	}
	path := remaining[:index]
	path = strings.ReplaceAll(path, "~1", "/")
	path = strings.ReplaceAll(path, "~0", "~")
	return path, remaining[index+1:]
}

func canonicalVectorFieldV1(fields []WireFieldDescriptorV1, path string) (WireFieldDescriptorV1, bool) {
	for _, field := range fields {
		if field.FieldPath == path {
			return field, true
		}
	}
	return WireFieldDescriptorV1{}, false
}

func canonicalVectorPredicateV1(predicates []PredicateDescriptorV1, id string) (PredicateDescriptorV1, bool) {
	for _, predicate := range predicates {
		if predicate.PredicateID == id {
			return predicate, true
		}
	}
	return PredicateDescriptorV1{}, false
}

func wrongJSONTypeV1(kind WireJSONType) json.RawMessage {
	if kind == WireBoolean {
		return []byte(`"wrong"`)
	}
	if kind == WireString {
		return []byte("false")
	}
	return []byte(`"wrong"`)
}

func belowMinimumJSONV1(field WireFieldDescriptorV1, recordPositives map[string][]byte) (json.RawMessage, error) {
	switch field.JSONType {
	case WireString:
		minimum := uint64(0)
		if field.MinBytes != nil {
			minimum = *field.MinBytes
		}
		if minimum == 0 {
			return nil, errors.New("string has no below-minimum value")
		}
		return json.Marshal(strings.Repeat("a", int(minimum-1)))
	case WireInteger:
		minimum := uint64(0)
		if field.MinU64 != nil {
			minimum = *field.MinU64
		}
		if minimum == 0 {
			return nil, errors.New("integer has no below-minimum value")
		}
		return []byte(strconv.FormatUint(minimum-1, 10)), nil
	case WireArray:
		minimum := uint64(0)
		if field.MinItems != nil {
			minimum = *field.MinItems
		}
		if minimum == 0 {
			return nil, errors.New("array has no below-minimum value")
		}
		return arrayOfSizeJSONV1(field, minimum-1, recordPositives)
	}
	return nil, errors.New("descriptor has no below-minimum mutation")
}

func aboveMaximumJSONV1(field WireFieldDescriptorV1, recordPositives map[string][]byte) (json.RawMessage, error) {
	switch field.JSONType {
	case WireInteger:
		if field.MaxU64 == nil || *field.MaxU64 == ^uint64(0) {
			return nil, errors.New("integer has no above-maximum value")
		}
		return []byte(strconv.FormatUint(*field.MaxU64+1, 10)), nil
	case WireArray:
		if field.MaxItems == nil {
			return nil, errors.New("array has no maximum")
		}
		return arrayOfSizeJSONV1(field, *field.MaxItems+1, recordPositives)
	}
	return nil, errors.New("descriptor has no above-maximum mutation")
}

func oversizedJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	if field.MaxBytes == nil {
		return nil, errors.New("descriptor has no string maximum")
	}
	if field.JSONType == WireRawJSON {
		return []byte(`{"a":"` + strings.Repeat("a", int(*field.MaxBytes)) + `"}`), nil
	}
	if field.JSONType != WireString {
		return nil, errors.New("descriptor has no string maximum")
	}
	length := *field.MaxBytes + 1
	switch field.ValueType {
	case "ed25519PublicKeyHex", "ed25519SignatureHex", "ledgerEventID":
		length = *field.MaxBytes + 2
	case "v4LedgerEventID":
		// The frozen negative is the retained 32-byte/64-character form,
		// not an odd-length syntactic hex string.
		length = 64
	}
	return json.Marshal(strings.Repeat("a", int(length)))
}

func arrayOfSizeJSONV1(field WireFieldDescriptorV1, count uint64, positiveByRecord ...map[string][]byte) (json.RawMessage, error) {
	var recordPositives map[string][]byte
	if len(positiveByRecord) != 0 {
		recordPositives = positiveByRecord[0]
	}
	values := make([]json.RawMessage, 0, count)
	var literalElements []json.RawMessage
	if field.ValueType == "exact-literal-array" {
		if json.Unmarshal([]byte(field.LiteralValue), &literalElements) != nil || len(literalElements) == 0 {
			return nil, errors.New("exact literal array has no materializable element")
		}
	}
	for index := uint64(0); index < count; index++ {
		if len(literalElements) != 0 {
			values = append(values, append(json.RawMessage(nil), literalElements[index%uint64(len(literalElements))]...))
			continue
		}
		elementType := arrayElementTypeV1(field.ValueType)
		value := append(json.RawMessage(nil), recordPositives[elementType]...)
		var err error
		if len(value) == 0 {
			value, err = minimalArrayElementJSONV1(field, elementType, index)
		}
		if err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	return json.Marshal(values)
}

func mutateStringJSONV1(raw json.RawMessage, mutate func(string) string) (json.RawMessage, error) {
	var value string
	if json.Unmarshal(raw, &value) != nil {
		return nil, errors.New("mutation target is not a string")
	}
	return json.Marshal(mutate(value))
}

func uppercaseFirstAlphaV1(value string) string {
	data := []byte(value)
	for index, character := range data {
		if character >= 'a' && character <= 'f' {
			data[index] = character - ('a' - 'A')
			break
		}
	}
	return string(data)
}

func flipFirstHexV1(value string) string {
	if value == "" {
		return value
	}
	if value[0] == 'a' {
		return "b" + value[1:]
	}
	return "a" + value[1:]
}

func badCharacterJSONV1(field WireFieldDescriptorV1) (json.RawMessage, error) {
	valueType := field.ValueType
	if field.JSONType == WireArray {
		valueType = arrayElementTypeV1(field.ValueType)
	}
	var invalid json.RawMessage
	switch valueType {
	case "path":
		invalid, _ = json.Marshal("/a")
	case "absPath":
		invalid, _ = json.Marshal("a")
	case "authorityDomain":
		invalid, _ = json.Marshal("a/b")
	default:
		if isHexWireType(valueType) {
			length := 64
			if field.MinBytes != nil {
				length = int(*field.MinBytes)
			}
			invalid, _ = json.Marshal("g" + strings.Repeat("a", length-1))
		}
	}
	if len(invalid) != 0 {
		if field.JSONType == WireArray {
			return json.Marshal([]json.RawMessage{invalid})
		}
		return invalid, nil
	}
	return nil, errors.New("descriptor has no BAD_CHAR mutation")
}

func unsortedArrayJSONV1(field WireFieldDescriptorV1, raw json.RawMessage, positiveByRecord ...map[string][]byte) (json.RawMessage, error) {
	var values []json.RawMessage
	if json.Unmarshal(raw, &values) != nil {
		return nil, errors.New("mutation target is not an array")
	}
	if len(values) < 2 {
		var err error
		valuesRaw, err := arrayOfSizeJSONV1(field, 2, positiveByRecord...)
		if err != nil {
			return nil, err
		}
		if json.Unmarshal(valuesRaw, &values) != nil {
			return nil, errors.New("cannot grow set for unsorted mutation")
		}
	}
	values[0], values[1] = values[1], values[0]
	return json.Marshal(values)
}

func duplicateArrayMemberJSONV1(field WireFieldDescriptorV1, raw json.RawMessage, positiveByRecord ...map[string][]byte) (json.RawMessage, error) {
	var values []json.RawMessage
	if json.Unmarshal(raw, &values) != nil {
		return nil, errors.New("mutation target is not an array")
	}
	if len(values) == 0 {
		valuesRaw, err := arrayOfSizeJSONV1(field, 1, positiveByRecord...)
		if err != nil {
			return nil, err
		}
		if json.Unmarshal(valuesRaw, &values) != nil {
			return nil, errors.New("cannot populate set for duplicate-member mutation")
		}
	}
	values = append(values, append(json.RawMessage(nil), values[0]...))
	sort.Slice(values, func(i, j int) bool { return bytes.Compare(values[i], values[j]) < 0 })
	return json.Marshal(values)
}

func scalarForDescriptorV1(field WireFieldDescriptorV1, value string) (json.RawMessage, error) {
	switch field.JSONType {
	case WireBoolean, WireInteger, WireArray:
		return []byte(value), nil
	default:
		return json.Marshal(value)
	}
}

func mutatePredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, values map[string]json.RawMessage, recordPositives map[string][]byte) error {
	fields := make(map[string]WireFieldDescriptorV1, len(entry.Fields))
	for _, field := range entry.Fields {
		fields[field.FieldPath] = field
	}
	paths := canonicalPredicateOperandPathsV1(entry, predicate, fields)
	if len(paths) == 0 {
		return fmt.Errorf("predicate %s has no executable field operands in %q", predicate.PredicateID, strings.Join(predicate.Arguments, " "))
	}
	switch predicate.Operator {
	case PredicateExactLiteral:
		field := fields[paths[0]]
		changed, err := ConstantChangedV1(field)
		if err != nil {
			return err
		}
		values[paths[0]], err = scalarForDescriptorV1(field, changed)
		return err
	case PredicateAllEqual:
		if len(paths) == 0 {
			return errors.New("ALL_EQUAL requires an operand")
		}
		field := fields[paths[0]]
		changed, err := primitiveValidChangeV1(field, values[paths[0]])
		if err != nil {
			return err
		}
		values[paths[0]] = changed
	case PredicateExactlyOne:
		for _, path := range paths {
			if _, present := values[path]; !present {
				value, err := minimalDescriptorJSON(fields[path])
				if err != nil {
					return err
				}
				values[path] = value
				return nil
			}
		}
		delete(values, paths[len(paths)-1])
	case PredicateOrdinalSuccess:
		integerPaths := integerPredicatePathsV1(paths, fields)
		if len(integerPaths) == 0 {
			return errors.New("ORDINAL_SUCCESSOR requires an integer operand")
		}
		if len(integerPaths) == 1 {
			var value uint64
			if json.Unmarshal(values[integerPaths[0]], &value) != nil {
				return errors.New("ordinal operand is invalid")
			}
			values[integerPaths[0]] = []byte(strconv.FormatUint(value+1, 10))
			break
		}
		var successor uint64
		if json.Unmarshal(values[integerPaths[1]], &successor) != nil || successor == ^uint64(0) {
			return errors.New("ordinal successor is invalid")
		}
		values[integerPaths[1]] = []byte(strconv.FormatUint(successor+1, 10))
	case PredicateSubset:
		arrayPaths := make([]string, 0, len(paths))
		for _, path := range paths {
			if fields[path].JSONType == WireArray {
				arrayPaths = append(arrayPaths, path)
			}
		}
		if len(arrayPaths) < 2 {
			for _, field := range entry.Fields {
				if field.JSONType == WireArray && !containsCanonicalVectorStringV1(arrayPaths, field.FieldPath) {
					arrayPaths = append(arrayPaths, field.FieldPath)
				}
			}
		}
		if len(arrayPaths) == 0 {
			return errors.New("SUBSET requires an array operand")
		}
		field := fields[arrayPaths[0]]
		var subset, superset []json.RawMessage
		if json.Unmarshal(values[arrayPaths[0]], &subset) != nil || len(arrayPaths) < 2 || json.Unmarshal(values[arrayPaths[1]], &superset) != nil {
			return errors.New("SUBSET operands are invalid")
		}
		members := make(map[string]struct{}, len(superset))
		for _, member := range superset {
			members[string(member)] = struct{}{}
		}
		var candidate json.RawMessage
		for ordinal := uint64(0); ordinal < 256; ordinal++ {
			next, err := minimalArrayElementJSONV1(field, arrayElementTypeV1(field.ValueType), ordinal)
			if err != nil {
				return err
			}
			if _, exists := members[string(next)]; !exists {
				candidate = next
				break
			}
		}
		if len(candidate) == 0 {
			return errors.New("SUBSET has no primitive-minimal foreign member")
		}
		subset = append(subset, candidate)
		if strings.Contains(field.ValueType, "(set") {
			sort.Slice(subset, func(i, j int) bool { return bytes.Compare(subset[i], subset[j]) < 0 })
		}
		values[arrayPaths[0]], _ = json.Marshal(subset)
	case PredicateDigestPreimage:
		candidates := append([]string(nil), paths...)
		outputs := make(map[string]struct{})
		for _, path := range paths {
			field := fields[path]
			if field.DigestTarget != "" || strings.HasSuffix(path, "_sha256") || path == "event_id" {
				outputs[path] = struct{}{}
			}
		}
		for _, field := range entry.Fields {
			if !containsCanonicalVectorStringV1(candidates, field.FieldPath) {
				candidates = append(candidates, field.FieldPath)
			}
		}
		for _, path := range candidates {
			field := fields[path]
			if _, output := outputs[path]; output {
				continue
			}
			raw, present := values[path]
			if !present {
				continue
			}
			changed, err := primitiveValidChangeV1(field, raw)
			if err == nil {
				values[path] = changed
				return nil
			}
		}
		return errors.New("digest preimage has no primitive-valid mutable operand")
	case PredicateTypedReference:
		for _, path := range paths {
			field := fields[path]
			raw, present := values[path]
			if !present {
				var err error
				raw, err = descriptorPositiveForMutationV1(field, nil)
				if err != nil {
					continue
				}
				values[path] = raw
			}
			if field.DigestTarget == "" {
				baseline := minimalCanonicalPredicateValuesV1(entry)[path]
				if len(baseline) == 0 {
					baseline = raw
				}
				changed, err := primitiveValidChangeV1(field, baseline)
				if err != nil {
					continue
				}
				values[path] = changed
				return nil
			}
			foreign, err := foreignTypedReferenceJSONV1(field, recordPositives)
			if err != nil {
				continue
			}
			if field.JSONType == WireArray {
				var elements []json.RawMessage
				if json.Unmarshal(raw, &elements) != nil {
					continue
				}
				if len(elements) == 0 {
					populated, err := arrayOfSizeJSONV1(field, 1)
					if err != nil || json.Unmarshal(populated, &elements) != nil {
						continue
					}
				}
				elements[0] = foreign
				values[path], _ = json.Marshal(elements)
				return nil
			}
			values[path] = foreign
			return nil
		}
		return errors.New("typed reference has no descriptor-valid substitution")
	case PredicateDerivation:
		path := canonicalDerivedOutputPathV1(entry, predicate, fields)
		field := fields[path]
		if _, present := values[path]; !present {
			var err error
			values[path], err = minimalDescriptorJSON(field)
			if err != nil {
				return err
			}
		}
		changed, err := primitiveValidChangeV1(field, values[path])
		if err != nil {
			return err
		}
		values[path] = changed
	case PredicateStateTransition:
		return mutateFrozenStatePredicateV1(entry, predicate, paths, fields, values)
	case PredicateIfAndOnlyIf, PredicateImplies:
		return mutateFrozenImplicationPredicateV1(entry, predicate, paths, fields, values)
	case PredicateAggregateLEQ:
		integerPaths := integerPredicatePathsV1(paths, fields)
		if len(integerPaths) < 2 {
			return errors.New("aggregate requires addend and limit")
		}
		var sum uint64
		for _, path := range integerPaths[:len(integerPaths)-1] {
			var addend uint64
			if json.Unmarshal(values[path], &addend) != nil || ^uint64(0)-sum < addend {
				return errors.New("aggregate addend is invalid")
			}
			sum += addend
		}
		var limit uint64
		if json.Unmarshal(values[integerPaths[len(integerPaths)-1]], &limit) != nil {
			return errors.New("aggregate limit is invalid")
		}
		if sum > limit || limit == ^uint64(0) {
			return errors.New("aggregate positive is not within its limit")
		}
		var lowest uint64
		if json.Unmarshal(values[integerPaths[0]], &lowest) != nil || ^uint64(0)-lowest < limit-sum+1 {
			return errors.New("aggregate mutation overflows")
		}
		values[integerPaths[0]] = []byte(strconv.FormatUint(lowest+(limit-sum+1), 10))
	default:
		return errors.New("predicate operator is not executable")
	}
	return nil
}

func foreignTypedReferenceJSONV1(field WireFieldDescriptorV1, recordPositives map[string][]byte) (json.RawMessage, error) {
	names := make([]string, 0, len(recordPositives))
	for name := range recordPositives {
		if name != field.DigestTarget {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	var foreign []byte
	if len(names) != 0 {
		foreign = recordPositives[names[0]]
	}
	if len(foreign) == 0 {
		foreign = []byte("CanonicalVectorEntryV1")
	}
	digest := sha256Hex(foreign)
	elementField := field
	if field.JSONType == WireArray {
		elementType := arrayElementTypeV1(field.ValueType)
		resolved, err := ResolveWireFieldDescriptorV1(field.SchemaID, field.FieldPath, field.Ordinal, elementType, false)
		if err != nil {
			return nil, err
		}
		elementField = resolved
	}
	if elementField.JSONType != WireString || validateCanonicalDescriptorValueV1(elementField, mustMarshalCanonicalVectorStringV1(digest)) != "" {
		return nil, errors.New("typed reference substitution is not descriptor-valid")
	}
	return mustMarshalCanonicalVectorStringV1(digest), nil
}

func mustMarshalCanonicalVectorStringV1(value string) json.RawMessage {
	encoded, _ := json.Marshal(value)
	return encoded
}

func mutateFrozenImplicationPredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, paths []string, fields map[string]WireFieldDescriptorV1, values map[string]json.RawMessage) error {
	setString := func(path, value string) { values[path] = mustMarshalCanonicalVectorStringV1(value) }
	switch predicate.PredicateID {
	case "P-PUBLISHER-001":
		setString("lifecycle", "ABANDONED")
		return nil
	case "P-PUBLISHER-002":
		setString("lifecycle", "ABANDONED")
		delete(values, "terminal_revision")
		delete(values, "terminal_operation")
		delete(values, "recovery_proof_sha256")
		return nil
	case "P-SUBJECT-001":
		values["diff_candidate_oid"] = mustMarshalCanonicalVectorStringV1(strings.Repeat("b", 40))
		return nil
	}
	if len(paths) < 2 {
		return errors.New("implication requires antecedent and consequent")
	}
	expected := minimalCanonicalPredicateValuesV1(entry)
	values[paths[0]] = append(json.RawMessage(nil), expected[paths[0]]...)
	consequent := paths[1]
	field := fields[consequent]
	if _, expectedPresent := expected[consequent]; !expectedPresent {
		value, err := descriptorPositiveForMutationV1(field, nil)
		if err != nil {
			return err
		}
		values[consequent] = value
		return nil
	}
	if field.Optional {
		delete(values, consequent)
		return nil
	}
	if fields[paths[0]].JSONType == WireBoolean && field.JSONType == WireBoolean {
		values[paths[0]] = []byte("true")
		values[consequent] = []byte("false")
		return nil
	}
	if field.JSONType == WireBoolean {
		values[consequent] = []byte("false")
		return nil
	}
	changed, err := primitiveValidChangeV1(field, expected[consequent])
	if err != nil {
		return err
	}
	values[consequent] = changed
	return nil
}

func mutateFrozenStatePredicateV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, paths []string, fields map[string]WireFieldDescriptorV1, values map[string]json.RawMessage) error {
	setString := func(path, value string) { values[path] = mustMarshalCanonicalVectorStringV1(value) }
	switch predicate.PredicateID {
	case "P-BARRIER-001":
		changed, err := primitiveValidChangeV1(fields["commitment"], values["commitment"])
		if err != nil {
			return err
		}
		values["commitment"] = changed
		return nil
	case "P-EVENT-001":
		setString("state_to", "a")
		return nil
	case "P-BARRIER-008":
		setString("applied_state_to", "a")
		return nil
	case "P-PUBLISHER-006":
		values["expires_at"] = append(json.RawMessage(nil), values["valid_from"]...)
		return nil
	case "P-predecessor-writer-lease-v1-ROW-001":
		setString("lease_state", "RELEASED")
		return nil
	case "P-RESOURCE-002":
		setString("lifecycle", "RELEASED")
		delete(values, "released_at_revision")
		delete(values, "release_evidence_sha256")
		return nil
	}
	if len(paths) >= 2 {
		edges := frozenTransitionEdgesV1(predicate)
		if len(edges) != 0 {
			var source string
			if json.Unmarshal(values[paths[0]], &source) != nil {
				return errors.New("state transition source is invalid")
			}
			members := canonicalClosedEnumMembersV1(fields[paths[1]])
			for _, destination := range members {
				if !edges[source+"\x00"+destination] {
					setString(paths[1], destination)
					return nil
				}
			}
			return errors.New("state transition has no closed-enum invalid destination")
		}
	}
	path := canonicalStateDestinationPathV1(entry, predicate, paths)
	if path == "" {
		return errors.New("state transition has no destination")
	}
	field := fields[path]
	if _, present := values[path]; !present {
		value, err := descriptorPositiveForMutationV1(field, nil)
		if err != nil {
			return err
		}
		values[path] = value
	}
	changed, err := primitiveValidChangeV1(field, values[path])
	if err != nil {
		return err
	}
	values[path] = changed
	return nil
}

var frozenTransitionEdgePatternV1 = regexp.MustCompile(`([A-Z][A-Z0-9_]*)\s*(?:→|->)\s*([A-Z][A-Z0-9_]*)`)

func frozenTransitionEdgesV1(predicate PredicateDescriptorV1) map[string]bool {
	edges := make(map[string]bool)
	for _, argument := range predicate.Arguments {
		for _, match := range frozenTransitionEdgePatternV1.FindAllStringSubmatch(argument, -1) {
			edges[match[1]+"\x00"+match[2]] = true
		}
	}
	return edges
}

func canonicalClosedEnumMembersV1(field WireFieldDescriptorV1) []string {
	if members, ok := frozenEnumValues[field.ValueType]; ok {
		return append([]string(nil), members...)
	}
	if strings.HasPrefix(field.ValueType, "{") && strings.HasSuffix(field.ValueType, "}") {
		parts := strings.Split(strings.Trim(field.ValueType, "{}"), ",")
		result := make([]string, 0, len(parts))
		for _, part := range parts {
			if member := strings.TrimSpace(part); member != "" {
				result = append(result, member)
			}
		}
		sort.Strings(result)
		return result
	}
	return nil
}

func containsCanonicalVectorStringV1(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func canonicalPredicateOperandPathsV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, fields map[string]WireFieldDescriptorV1) []string {
	result := make([]string, 0, len(entry.Fields))
	appendPath := func(path string) {
		if path == "" || path == "$" || containsCanonicalVectorStringV1(result, path) {
			return
		}
		if _, exists := fields[path]; exists {
			result = append(result, path)
		}
	}
	for _, path := range predicate.FieldPaths {
		appendPath(path)
	}
	arguments := strings.Join(predicate.Arguments, " ")
	for _, field := range entry.Fields {
		if containsFieldToken(arguments, field.FieldPath) {
			appendPath(field.FieldPath)
		}
	}
	if predicate.Operator == PredicateSubset {
		arrays := result[:0]
		for _, path := range result {
			if fields[path].JSONType == WireArray {
				arrays = append(arrays, path)
			}
		}
		result = arrays
	}
	if predicate.Operator == PredicateExactlyOne {
		optional := result[:0]
		for _, path := range result {
			if fields[path].Optional {
				optional = append(optional, path)
			}
		}
		result = optional
	}
	if predicate.Operator == PredicateTypedReference {
		references := result[:0]
		for _, path := range result {
			if fields[path].DigestTarget != "" {
				references = append(references, path)
			}
		}
		if len(references) == 0 {
			for _, field := range entry.Fields {
				if field.DigestTarget != "" && !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, int(field.Ordinal-1)) {
					references = append(references, field.FieldPath)
				}
			}
		}
		result = references
	}

	eligible := func(index int, field WireFieldDescriptorV1) bool {
		if field.LiteralValue != "" || isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, index) {
			return false
		}
		switch predicate.Operator {
		case PredicateSubset:
			return field.JSONType == WireArray
		case PredicateOrdinalSuccess, PredicateAggregateLEQ:
			return field.JSONType == WireInteger
		case PredicateExactlyOne:
			return field.Optional
		case PredicateIfAndOnlyIf:
			return field.JSONType == WireBoolean || field.Optional
		case PredicateImplies:
			return field.JSONType != WireObject && field.JSONType != WireRawJSON
		case PredicateAllEqual:
			if len(result) == 0 {
				return field.JSONType != WireObject && field.JSONType != WireRawJSON
			}
			return field.ValueType == fields[result[0]].ValueType
		default:
			return field.JSONType != WireObject && field.JSONType != WireRawJSON
		}
	}

	minimum := predicateOperandCountV1(predicate.Operator)
	if predicate.Operator == PredicateAggregateLEQ {
		// The frozen aggregate operands are every numeric addend followed by the
		// limit. A prose extractor may have named a nearby boolean instead.
		result = result[:0]
		for _, field := range entry.Fields {
			if field.JSONType == WireInteger {
				result = append(result, field.FieldPath)
			}
		}
		return result
	}
	if predicate.Operator == PredicateOrdinalSuccess {
		integers := integerPredicatePathsV1(result, fields)
		if len(integers) >= minimum {
			return integers
		}
		result = integers
	}
	for index, field := range entry.Fields {
		if len(result) >= minimum && predicate.Operator != PredicateExactlyOne {
			break
		}
		if eligible(index, field) {
			appendPath(field.FieldPath)
		}
	}
	if (predicate.Operator == PredicateAllEqual || predicate.Operator == PredicateOrdinalSuccess) && len(result) != 0 {
		return result
	}
	if len(result) < minimum {
		for index, field := range entry.Fields {
			if field.LiteralValue == "" && !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, index) {
				appendPath(field.FieldPath)
				if len(result) >= minimum {
					break
				}
			}
		}
	}
	return result
}

func canonicalDerivedOutputPathV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, fields map[string]WireFieldDescriptorV1) string {
	switch predicate.PredicateID {
	case "P-DIFF-001":
		return "derivation_rule"
	case "P-effect-pre-call-closure-v1-ROW-001":
		for _, candidate := range []string{"claim_sha256", "call_admission_sha256", "unclaimed_abandonment_sha256"} {
			if _, ok := fields[candidate]; ok {
				return candidate
			}
		}
	case "P-PR-002":
		for _, candidate := range []string{"mutation_mode", "route_template", "request_body"} {
			if _, ok := fields[candidate]; ok {
				return candidate
			}
		}
	case "P-MERGE-003":
		for _, candidate := range []string{"observation_source", "read_request_sha256s"} {
			if _, ok := fields[candidate]; ok {
				return candidate
			}
		}
	}
	paths := canonicalPredicateOperandPathsV1(entry, predicate, fields)
	if len(paths) == 0 {
		return ""
	}
	return paths[len(paths)-1]
}

func canonicalStateDestinationPathV1(entry CanonicalVectorEntryV1, predicate PredicateDescriptorV1, paths []string) string {
	for index := len(paths) - 1; index >= 0; index-- {
		field, ok := canonicalVectorFieldV1(entry.Fields, paths[index])
		if ok && (isClosedEnumType(field.ValueType) || strings.HasPrefix(field.ValueType, "{")) {
			return paths[index]
		}
	}
	if len(paths) != 0 {
		return paths[len(paths)-1]
	}
	return ""
}

func predicateOperandCountV1(operator PredicateOperator) int {
	switch operator {
	case PredicateAllEqual, PredicateIfAndOnlyIf, PredicateImplies, PredicateSubset, PredicateOrdinalSuccess, PredicateAggregateLEQ, PredicateExactlyOne:
		return 2
	default:
		return 1
	}
}

func primitiveValidChangeV1(field WireFieldDescriptorV1, raw json.RawMessage) (json.RawMessage, error) {
	switch field.JSONType {
	case WireArray:
		var values []json.RawMessage
		if json.Unmarshal(raw, &values) != nil {
			return nil, errors.New("array operand is invalid")
		}
		if len(values) == 0 {
			if field.MaxItems != nil && *field.MaxItems == 0 {
				return nil, errors.New("array operand cannot change cardinality")
			}
			value, err := minimalArrayElementJSONV1(field, arrayElementTypeV1(field.ValueType), 0)
			if err != nil {
				return nil, err
			}
			return json.Marshal([]json.RawMessage{value})
		}
		elementType := arrayElementTypeV1(field.ValueType)
		element, err := ResolveWireFieldDescriptorV1(field.SchemaID, field.FieldPath, field.Ordinal, elementType, false)
		if err != nil {
			return nil, err
		}
		changed, err := primitiveValidChangeV1(element, values[0])
		if err != nil {
			return nil, err
		}
		values[0] = changed
		if strings.Contains(field.ValueType, "(set") {
			sort.Slice(values, func(i, j int) bool { return bytes.Compare(values[i], values[j]) < 0 })
		}
		return json.Marshal(values)
	case WireObject:
		values, order, duplicate, err := decodeCanonicalVectorObjectV1(raw)
		if err != nil || duplicate {
			return nil, errors.New("object operand is invalid")
		}
		for _, name := range order {
			var value uint64
			if json.Unmarshal(values[name], &value) == nil && value < uint64(^uint64(0)) {
				values[name] = []byte(strconv.FormatUint(value+1, 10))
				return marshalCanonicalRawObjectV1(order, values), nil
			}
		}
		for _, name := range order {
			var value bool
			if string(values[name]) != "true" && string(values[name]) != "false" {
				continue
			}
			if json.Unmarshal(values[name], &value) == nil {
				values[name] = []byte(strconv.FormatBool(!value))
				return marshalCanonicalRawObjectV1(order, values), nil
			}
		}
	case WireString:
		var value string
		if json.Unmarshal(raw, &value) != nil {
			return nil, errors.New("string operand is invalid")
		}
		if field.ValueType == "procStart" {
			number, err := strconv.ParseUint(value, 10, 64)
			if err == nil && number != ^uint64(0) {
				return json.Marshal(strconv.FormatUint(number+1, 10))
			}
		}
		if members, ok := frozenEnumValues[field.ValueType]; ok {
			for _, member := range members {
				if member != value {
					return json.Marshal(member)
				}
			}
		}
		if strings.HasPrefix(field.ValueType, "{") && strings.HasSuffix(field.ValueType, "}") {
			for _, member := range strings.Split(strings.Trim(field.ValueType, "{}"), ",") {
				member = strings.TrimSpace(member)
				if member != "" && member != value {
					return json.Marshal(member)
				}
			}
		}
		if isHexWireType(field.ValueType) {
			return json.Marshal(flipFirstHexV1(value))
		}
		for index := len(value) - 1; index >= 0; index-- {
			for _, replacement := range []byte{'a', 'b', '0', '1', '-', '_'} {
				if value[index] == replacement {
					continue
				}
				candidate := value[:index] + string(replacement) + value[index+1:]
				if ValidatePrimitiveWireValueV1(field.ValueType, candidate) == nil {
					return json.Marshal(candidate)
				}
			}
		}
	case WireInteger:
		var value uint64
		if json.Unmarshal(raw, &value) == nil && (field.MaxU64 == nil || value < *field.MaxU64) {
			return []byte(strconv.FormatUint(value+1, 10)), nil
		}
	case WireBoolean:
		var value bool
		if json.Unmarshal(raw, &value) == nil {
			return []byte(strconv.FormatBool(!value)), nil
		}
	}
	return nil, errors.New("operand has no primitive-valid change")
}

func marshalCanonicalRawObjectV1(order []string, values map[string]json.RawMessage) []byte {
	var result bytes.Buffer
	result.WriteByte('{')
	for index, name := range order {
		if index != 0 {
			result.WriteByte(',')
		}
		encodedName, _ := json.Marshal(name)
		result.Write(encodedName)
		result.WriteByte(':')
		result.Write(values[name])
	}
	result.WriteByte('}')
	return result.Bytes()
}

func resealDependentDigestsV1(entry CanonicalVectorEntryV1, values map[string]json.RawMessage, changed []string) ([]byte, error) {
	changedSet := make(map[string]struct{}, len(changed))
	for _, path := range changed {
		changedSet[path] = struct{}{}
	}
	for fieldIndex, field := range entry.Fields {
		if !isSelfDigestFieldIndexV1(entry.RecordName, entry.SchemaID, entry.Fields, fieldIndex) {
			continue
		}
		if _, directlyChanged := changedSet[field.FieldPath]; directlyChanged {
			continue
		}
		preimage, err := marshalCanonicalVectorObjectV1(entry.Fields, values, field.FieldPath)
		if err != nil {
			return nil, err
		}
		values[field.FieldPath], _ = json.Marshal(sha256Hex(preimage))
	}
	return marshalCanonicalVectorObjectV1(entry.Fields, values, "")
}

// VerifyEd25519CanonicalVectorV1 proves the frozen wire widths and signature
// against the same message bytes used by positive generation.
func VerifyEd25519CanonicalVectorV1(publicKeyHex, signatureHex string, message []byte) error {
	publicKey, err := hex.DecodeString(publicKeyHex)
	if err != nil || len(publicKey) != ed25519.PublicKeySize {
		return errors.New("Ed25519 public key must be exactly 32 raw bytes")
	}
	signature, err := hex.DecodeString(signatureHex)
	if err != nil || len(signature) != ed25519.SignatureSize {
		return errors.New("Ed25519 signature must be exactly 64 raw bytes")
	}
	if publicKeyHex != strings.ToLower(publicKeyHex) || signatureHex != strings.ToLower(signatureHex) {
		return errors.New("Ed25519 wire must be lower-hex")
	}
	if !ed25519.Verify(ed25519.PublicKey(publicKey), message, signature) {
		return errors.New("Ed25519 signature verification failed")
	}
	return nil
}
